// To parse this JSON:
// 
//   NSError *error;
//   APIData *data = [APIData fromJSON:json encoding:NSUTF8Encoding error:&error];
//   APIEmojis *emojis = [APIEmojis fromJSON:json encoding:NSUTF8Encoding error:&error];
//   APIEvents *events = APIEventsFromJSON(json, NSUTF8Encoding, &error);
//   APIGists *gists = APIGistsFromJSON(json, NSUTF8Encoding, &error);
//   APIMeta *meta = [APIMeta fromJSON:json encoding:NSUTF8Encoding error:&error];

#import <Foundation/Foundation.h>

@class APIData;
@class APIEmojis;
@class APIEvent;
@class APIActor;
@class APIGravatarID;
@class APIPayload;
@class APIComment;
@class APIUser;
@class APIUserType;
@class APICommit;
@class APIAuthor;
@class APIForkee;
@class APIIssue;
@class APILabel;
@class APIPullRequest;
@class APIBase;
@class APILinks;
@class APIComments;
@class APIRepo;
@class APIGist;
@class APIFile;
@class APIFileType;
@class APIMeta;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Boxed enums

@interface APIGravatarID : NSObject
@property (nonatomic, readonly, copy) NSString *value;
+ (instancetype _Nullable)withValue:(NSString *)value;
+ (APIGravatarID *)empty;
@end

@interface APIUserType : NSObject
@property (nonatomic, readonly, copy) NSString *value;
+ (instancetype _Nullable)withValue:(NSString *)value;
+ (APIUserType *)organization;
+ (APIUserType *)user;
@end

@interface APIFileType : NSObject
@property (nonatomic, readonly, copy) NSString *value;
+ (instancetype _Nullable)withValue:(NSString *)value;
+ (APIFileType *)applicationJavascript;
+ (APIFileType *)applicationXPython;
+ (APIFileType *)textCSS;
+ (APIFileType *)textHTML;
+ (APIFileType *)textPlain;
@end

typedef NSArray<APIEvent *> APIEvents;

typedef NSArray<APIGist *> APIGists;

#pragma mark - Top-level marshaling functions

APIEvents *_Nullable APIEventsFromData(NSData *data, NSError **error);
APIEvents *_Nullable APIEventsFromJSON(NSString *json, NSStringEncoding encoding, NSError **error);
NSData    *_Nullable APIEventsToData(APIEvents *events, NSError **error);
NSString  *_Nullable APIEventsToJSON(APIEvents *events, NSStringEncoding encoding, NSError **error);

APIGists *_Nullable APIGistsFromData(NSData *data, NSError **error);
APIGists *_Nullable APIGistsFromJSON(NSString *json, NSStringEncoding encoding, NSError **error);
NSData   *_Nullable APIGistsToData(APIGists *gists, NSError **error);
NSString *_Nullable APIGistsToJSON(APIGists *gists, NSStringEncoding encoding, NSError **error);

#pragma mark - Object interfaces

@interface APIData : NSObject
@property (nonatomic, copy) NSString *currentUserURL;
@property (nonatomic, copy) NSString *currentUserAuthorizationsHTMLURL;
@property (nonatomic, copy) NSString *authorizationsURL;
@property (nonatomic, copy) NSString *codeSearchURL;
@property (nonatomic, copy) NSString *commitSearchURL;
@property (nonatomic, copy) NSString *emailsURL;
@property (nonatomic, copy) NSString *emojisURL;
@property (nonatomic, copy) NSString *eventsURL;
@property (nonatomic, copy) NSString *feedsURL;
@property (nonatomic, copy) NSString *followersURL;
@property (nonatomic, copy) NSString *followingURL;
@property (nonatomic, copy) NSString *gistsURL;
@property (nonatomic, copy) NSString *hubURL;
@property (nonatomic, copy) NSString *issueSearchURL;
@property (nonatomic, copy) NSString *issuesURL;
@property (nonatomic, copy) NSString *keysURL;
@property (nonatomic, copy) NSString *notificationsURL;
@property (nonatomic, copy) NSString *organizationRepositoriesURL;
@property (nonatomic, copy) NSString *organizationURL;
@property (nonatomic, copy) NSString *publicGistsURL;
@property (nonatomic, copy) NSString *rateLimitURL;
@property (nonatomic, copy) NSString *repositoryURL;
@property (nonatomic, copy) NSString *repositorySearchURL;
@property (nonatomic, copy) NSString *currentUserRepositoriesURL;
@property (nonatomic, copy) NSString *starredURL;
@property (nonatomic, copy) NSString *starredGistsURL;
@property (nonatomic, copy) NSString *teamURL;
@property (nonatomic, copy) NSString *userURL;
@property (nonatomic, copy) NSString *userOrganizationsURL;
@property (nonatomic, copy) NSString *userRepositoriesURL;
@property (nonatomic, copy) NSString *userSearchURL;

+ (_Nullable instancetype)fromJSON:(NSString *)json encoding:(NSStringEncoding)encoding error:(NSError *_Nullable *)error;
+ (_Nullable instancetype)fromData:(NSData *)data error:(NSError *_Nullable *)error;
- (NSString *_Nullable)toJSON:(NSStringEncoding)encoding error:(NSError *_Nullable *)error;
- (NSData *_Nullable)toData:(NSError *_Nullable *)error;
@end

@interface APIEmojis : NSObject
@property (nonatomic, copy) NSString *the1;
@property (nonatomic, copy) NSString *emojis1;
@property (nonatomic, copy) NSString *the100;
@property (nonatomic, copy) NSString *the1234;
@property (nonatomic, copy) NSString *the1StPlaceMedal;
@property (nonatomic, copy) NSString *the2NdPlaceMedal;
@property (nonatomic, copy) NSString *the3RDPlaceMedal;
@property (nonatomic, copy) NSString *the8Ball;
@property (nonatomic, copy) NSString *a;
@property (nonatomic, copy) NSString *ab;
@property (nonatomic, copy) NSString *abc;
@property (nonatomic, copy) NSString *abcd;
@property (nonatomic, copy) NSString *accept;
@property (nonatomic, copy) NSString *aerialTramway;
@property (nonatomic, copy) NSString *afghanistan;
@property (nonatomic, copy) NSString *airplane;
@property (nonatomic, copy) NSString *alandIslands;
@property (nonatomic, copy) NSString *alarmClock;
@property (nonatomic, copy) NSString *albania;
@property (nonatomic, copy) NSString *alembic;
@property (nonatomic, copy) NSString *algeria;
@property (nonatomic, copy) NSString *alien;
@property (nonatomic, copy) NSString *ambulance;
@property (nonatomic, copy) NSString *americanSamoa;
@property (nonatomic, copy) NSString *amphora;
@property (nonatomic, copy) NSString *anchor;
@property (nonatomic, copy) NSString *andorra;
@property (nonatomic, copy) NSString *angel;
@property (nonatomic, copy) NSString *anger;
@property (nonatomic, copy) NSString *angola;
@property (nonatomic, copy) NSString *angry;
@property (nonatomic, copy) NSString *anguilla;
@property (nonatomic, copy) NSString *anguished;
@property (nonatomic, copy) NSString *ant;
@property (nonatomic, copy) NSString *antarctica;
@property (nonatomic, copy) NSString *antiguaBarbuda;
@property (nonatomic, copy) NSString *apple;
@property (nonatomic, copy) NSString *aquarius;
@property (nonatomic, copy) NSString *argentina;
@property (nonatomic, copy) NSString *aries;
@property (nonatomic, copy) NSString *armenia;
@property (nonatomic, copy) NSString *arrowBackward;
@property (nonatomic, copy) NSString *arrowDoubleDown;
@property (nonatomic, copy) NSString *arrowDoubleUp;
@property (nonatomic, copy) NSString *arrowDown;
@property (nonatomic, copy) NSString *arrowDownSmall;
@property (nonatomic, copy) NSString *arrowForward;
@property (nonatomic, copy) NSString *arrowHeadingDown;
@property (nonatomic, copy) NSString *arrowHeadingUp;
@property (nonatomic, copy) NSString *arrowLeft;
@property (nonatomic, copy) NSString *arrowLowerLeft;
@property (nonatomic, copy) NSString *arrowLowerRight;
@property (nonatomic, copy) NSString *arrowRight;
@property (nonatomic, copy) NSString *arrowRightHook;
@property (nonatomic, copy) NSString *arrowUp;
@property (nonatomic, copy) NSString *arrowUpDown;
@property (nonatomic, copy) NSString *arrowUpSmall;
@property (nonatomic, copy) NSString *arrowUpperLeft;
@property (nonatomic, copy) NSString *arrowUpperRight;
@property (nonatomic, copy) NSString *arrowsClockwise;
@property (nonatomic, copy) NSString *arrowsCounterclockwise;
@property (nonatomic, copy) NSString *art;
@property (nonatomic, copy) NSString *articulatedLorry;
@property (nonatomic, copy) NSString *artificialSatellite;
@property (nonatomic, copy) NSString *aruba;
@property (nonatomic, copy) NSString *asterisk;
@property (nonatomic, copy) NSString *astonished;
@property (nonatomic, copy) NSString *athleticShoe;
@property (nonatomic, copy) NSString *atm;
@property (nonatomic, copy) NSString *atom;
@property (nonatomic, copy) NSString *atomSymbol;
@property (nonatomic, copy) NSString *australia;
@property (nonatomic, copy) NSString *austria;
@property (nonatomic, copy) NSString *avocado;
@property (nonatomic, copy) NSString *azerbaijan;
@property (nonatomic, copy) NSString *b;
@property (nonatomic, copy) NSString *baby;
@property (nonatomic, copy) NSString *babyBottle;
@property (nonatomic, copy) NSString *babyChick;
@property (nonatomic, copy) NSString *babySymbol;
@property (nonatomic, copy) NSString *back;
@property (nonatomic, copy) NSString *bacon;
@property (nonatomic, copy) NSString *badminton;
@property (nonatomic, copy) NSString *baggageClaim;
@property (nonatomic, copy) NSString *baguetteBread;
@property (nonatomic, copy) NSString *bahamas;
@property (nonatomic, copy) NSString *bahrain;
@property (nonatomic, copy) NSString *balanceScale;
@property (nonatomic, copy) NSString *balloon;
@property (nonatomic, copy) NSString *ballotBox;
@property (nonatomic, copy) NSString *ballotBoxWithCheck;
@property (nonatomic, copy) NSString *bamboo;
@property (nonatomic, copy) NSString *banana;
@property (nonatomic, copy) NSString *bangbang;
@property (nonatomic, copy) NSString *bangladesh;
@property (nonatomic, copy) NSString *bank;
@property (nonatomic, copy) NSString *barChart;
@property (nonatomic, copy) NSString *barbados;
@property (nonatomic, copy) NSString *barber;
@property (nonatomic, copy) NSString *baseball;
@property (nonatomic, copy) NSString *basecamp;
@property (nonatomic, copy) NSString *basecampy;
@property (nonatomic, copy) NSString *basketball;
@property (nonatomic, copy) NSString *basketballMan;
@property (nonatomic, copy) NSString *basketballWoman;
@property (nonatomic, copy) NSString *bat;
@property (nonatomic, copy) NSString *bath;
@property (nonatomic, copy) NSString *bathtub;
@property (nonatomic, copy) NSString *battery;
@property (nonatomic, copy) NSString *beachUmbrella;
@property (nonatomic, copy) NSString *bear;
@property (nonatomic, copy) NSString *bed;
@property (nonatomic, copy) NSString *bee;
@property (nonatomic, copy) NSString *beer;
@property (nonatomic, copy) NSString *beers;
@property (nonatomic, copy) NSString *beetle;
@property (nonatomic, copy) NSString *beginner;
@property (nonatomic, copy) NSString *belarus;
@property (nonatomic, copy) NSString *belgium;
@property (nonatomic, copy) NSString *belize;
@property (nonatomic, copy) NSString *bell;
@property (nonatomic, copy) NSString *bellhopBell;
@property (nonatomic, copy) NSString *benin;
@property (nonatomic, copy) NSString *bento;
@property (nonatomic, copy) NSString *bermuda;
@property (nonatomic, copy) NSString *bhutan;
@property (nonatomic, copy) NSString *bicyclist;
@property (nonatomic, copy) NSString *bike;
@property (nonatomic, copy) NSString *bikingMan;
@property (nonatomic, copy) NSString *bikingWoman;
@property (nonatomic, copy) NSString *bikini;
@property (nonatomic, copy) NSString *biohazard;
@property (nonatomic, copy) NSString *bird;
@property (nonatomic, copy) NSString *birthday;
@property (nonatomic, copy) NSString *blackCircle;
@property (nonatomic, copy) NSString *blackFlag;
@property (nonatomic, copy) NSString *blackHeart;
@property (nonatomic, copy) NSString *blackJoker;
@property (nonatomic, copy) NSString *blackLargeSquare;
@property (nonatomic, copy) NSString *blackMediumSmallSquare;
@property (nonatomic, copy) NSString *blackMediumSquare;
@property (nonatomic, copy) NSString *blackNib;
@property (nonatomic, copy) NSString *blackSmallSquare;
@property (nonatomic, copy) NSString *blackSquareButton;
@property (nonatomic, copy) NSString *blondeMan;
@property (nonatomic, copy) NSString *blondeWoman;
@property (nonatomic, copy) NSString *blossom;
@property (nonatomic, copy) NSString *blowfish;
@property (nonatomic, copy) NSString *blueBook;
@property (nonatomic, copy) NSString *blueCar;
@property (nonatomic, copy) NSString *blueHeart;
@property (nonatomic, copy) NSString *blush;
@property (nonatomic, copy) NSString *boar;
@property (nonatomic, copy) NSString *boat;
@property (nonatomic, copy) NSString *bolivia;
@property (nonatomic, copy) NSString *bomb;
@property (nonatomic, copy) NSString *book;
@property (nonatomic, copy) NSString *bookmark;
@property (nonatomic, copy) NSString *bookmarkTabs;
@property (nonatomic, copy) NSString *books;
@property (nonatomic, copy) NSString *boom;
@property (nonatomic, copy) NSString *boot;
@property (nonatomic, copy) NSString *bosniaHerzegovina;
@property (nonatomic, copy) NSString *botswana;
@property (nonatomic, copy) NSString *bouquet;
@property (nonatomic, copy) NSString *bow;
@property (nonatomic, copy) NSString *bowAndArrow;
@property (nonatomic, copy) NSString *bowingMan;
@property (nonatomic, copy) NSString *bowingWoman;
@property (nonatomic, copy) NSString *bowling;
@property (nonatomic, copy) NSString *bowtie;
@property (nonatomic, copy) NSString *boxingGlove;
@property (nonatomic, copy) NSString *boy;
@property (nonatomic, copy) NSString *brazil;
@property (nonatomic, copy) NSString *bread;
@property (nonatomic, copy) NSString *brideWithVeil;
@property (nonatomic, copy) NSString *bridgeAtNight;
@property (nonatomic, copy) NSString *briefcase;
@property (nonatomic, copy) NSString *britishIndianOceanTerritory;
@property (nonatomic, copy) NSString *britishVirginIslands;
@property (nonatomic, copy) NSString *brokenHeart;
@property (nonatomic, copy) NSString *brunei;
@property (nonatomic, copy) NSString *bug;
@property (nonatomic, copy) NSString *buildingConstruction;
@property (nonatomic, copy) NSString *bulb;
@property (nonatomic, copy) NSString *bulgaria;
@property (nonatomic, copy) NSString *bullettrainFront;
@property (nonatomic, copy) NSString *bullettrainSide;
@property (nonatomic, copy) NSString *burkinaFaso;
@property (nonatomic, copy) NSString *burrito;
@property (nonatomic, copy) NSString *burundi;
@property (nonatomic, copy) NSString *bus;
@property (nonatomic, copy) NSString *businessSuitLevitating;
@property (nonatomic, copy) NSString *busstop;
@property (nonatomic, copy) NSString *bustInSilhouette;
@property (nonatomic, copy) NSString *bustsInSilhouette;
@property (nonatomic, copy) NSString *butterfly;
@property (nonatomic, copy) NSString *cactus;
@property (nonatomic, copy) NSString *cake;
@property (nonatomic, copy) NSString *calendar;
@property (nonatomic, copy) NSString *callMeHand;
@property (nonatomic, copy) NSString *calling;
@property (nonatomic, copy) NSString *cambodia;
@property (nonatomic, copy) NSString *camel;
@property (nonatomic, copy) NSString *camera;
@property (nonatomic, copy) NSString *cameraFlash;
@property (nonatomic, copy) NSString *cameroon;
@property (nonatomic, copy) NSString *camping;
@property (nonatomic, copy) NSString *canada;
@property (nonatomic, copy) NSString *canaryIslands;
@property (nonatomic, copy) NSString *cancer;
@property (nonatomic, copy) NSString *candle;
@property (nonatomic, copy) NSString *candy;
@property (nonatomic, copy) NSString *canoe;
@property (nonatomic, copy) NSString *capeVerde;
@property (nonatomic, copy) NSString *capitalAbcd;
@property (nonatomic, copy) NSString *capricorn;
@property (nonatomic, copy) NSString *car;
@property (nonatomic, copy) NSString *cardFileBox;
@property (nonatomic, copy) NSString *cardIndex;
@property (nonatomic, copy) NSString *cardIndexDividers;
@property (nonatomic, copy) NSString *caribbeanNetherlands;
@property (nonatomic, copy) NSString *carouselHorse;
@property (nonatomic, copy) NSString *carrot;
@property (nonatomic, copy) NSString *cat;
@property (nonatomic, copy) NSString *cat2;
@property (nonatomic, copy) NSString *caymanIslands;
@property (nonatomic, copy) NSString *cd;
@property (nonatomic, copy) NSString *centralAfricanRepublic;
@property (nonatomic, copy) NSString *chad;
@property (nonatomic, copy) NSString *chains;
@property (nonatomic, copy) NSString *champagne;
@property (nonatomic, copy) NSString *chart;
@property (nonatomic, copy) NSString *chartWithDownwardsTrend;
@property (nonatomic, copy) NSString *chartWithUpwardsTrend;
@property (nonatomic, copy) NSString *checkeredFlag;
@property (nonatomic, copy) NSString *cheese;
@property (nonatomic, copy) NSString *cherries;
@property (nonatomic, copy) NSString *cherryBlossom;
@property (nonatomic, copy) NSString *chestnut;
@property (nonatomic, copy) NSString *chicken;
@property (nonatomic, copy) NSString *childrenCrossing;
@property (nonatomic, copy) NSString *chile;
@property (nonatomic, copy) NSString *chipmunk;
@property (nonatomic, copy) NSString *chocolateBar;
@property (nonatomic, copy) NSString *christmasIsland;
@property (nonatomic, copy) NSString *christmasTree;
@property (nonatomic, copy) NSString *church;
@property (nonatomic, copy) NSString *cinema;
@property (nonatomic, copy) NSString *circusTent;
@property (nonatomic, copy) NSString *citySunrise;
@property (nonatomic, copy) NSString *citySunset;
@property (nonatomic, copy) NSString *cityscape;
@property (nonatomic, copy) NSString *cl;
@property (nonatomic, copy) NSString *clamp;
@property (nonatomic, copy) NSString *clap;
@property (nonatomic, copy) NSString *clapper;
@property (nonatomic, copy) NSString *classicalBuilding;
@property (nonatomic, copy) NSString *clinkingGlasses;
@property (nonatomic, copy) NSString *clipboard;
@property (nonatomic, copy) NSString *clock1;
@property (nonatomic, copy) NSString *clock10;
@property (nonatomic, copy) NSString *clock1030;
@property (nonatomic, copy) NSString *clock11;
@property (nonatomic, copy) NSString *clock1130;
@property (nonatomic, copy) NSString *clock12;
@property (nonatomic, copy) NSString *clock1230;
@property (nonatomic, copy) NSString *clock130;
@property (nonatomic, copy) NSString *clock2;
@property (nonatomic, copy) NSString *clock230;
@property (nonatomic, copy) NSString *clock3;
@property (nonatomic, copy) NSString *clock330;
@property (nonatomic, copy) NSString *clock4;
@property (nonatomic, copy) NSString *clock430;
@property (nonatomic, copy) NSString *clock5;
@property (nonatomic, copy) NSString *clock530;
@property (nonatomic, copy) NSString *clock6;
@property (nonatomic, copy) NSString *clock630;
@property (nonatomic, copy) NSString *clock7;
@property (nonatomic, copy) NSString *clock730;
@property (nonatomic, copy) NSString *clock8;
@property (nonatomic, copy) NSString *clock830;
@property (nonatomic, copy) NSString *clock9;
@property (nonatomic, copy) NSString *clock930;
@property (nonatomic, copy) NSString *closedBook;
@property (nonatomic, copy) NSString *closedLockWithKey;
@property (nonatomic, copy) NSString *closedUmbrella;
@property (nonatomic, copy) NSString *cloud;
@property (nonatomic, copy) NSString *cloudWithLightning;
@property (nonatomic, copy) NSString *cloudWithLightningAndRain;
@property (nonatomic, copy) NSString *cloudWithRain;
@property (nonatomic, copy) NSString *cloudWithSnow;
@property (nonatomic, copy) NSString *clownFace;
@property (nonatomic, copy) NSString *clubs;
@property (nonatomic, copy) NSString *cn;
@property (nonatomic, copy) NSString *cocktail;
@property (nonatomic, copy) NSString *cocosIslands;
@property (nonatomic, copy) NSString *coffee;
@property (nonatomic, copy) NSString *coffin;
@property (nonatomic, copy) NSString *coldSweat;
@property (nonatomic, copy) NSString *collision;
@property (nonatomic, copy) NSString *colombia;
@property (nonatomic, copy) NSString *comet;
@property (nonatomic, copy) NSString *comoros;
@property (nonatomic, copy) NSString *computer;
@property (nonatomic, copy) NSString *computerMouse;
@property (nonatomic, copy) NSString *confettiBall;
@property (nonatomic, copy) NSString *confounded;
@property (nonatomic, copy) NSString *confused;
@property (nonatomic, copy) NSString *congoBrazzaville;
@property (nonatomic, copy) NSString *congoKinshasa;
@property (nonatomic, copy) NSString *congratulations;
@property (nonatomic, copy) NSString *construction;
@property (nonatomic, copy) NSString *constructionWorker;
@property (nonatomic, copy) NSString *constructionWorkerMan;
@property (nonatomic, copy) NSString *constructionWorkerWoman;
@property (nonatomic, copy) NSString *controlKnobs;
@property (nonatomic, copy) NSString *convenienceStore;
@property (nonatomic, copy) NSString *cookIslands;
@property (nonatomic, copy) NSString *cookie;
@property (nonatomic, copy) NSString *cool;
@property (nonatomic, copy) NSString *cop;
@property (nonatomic, copy) NSString *copyright;
@property (nonatomic, copy) NSString *corn;
@property (nonatomic, copy) NSString *costaRica;
@property (nonatomic, copy) NSString *coteDivoire;
@property (nonatomic, copy) NSString *couchAndLamp;
@property (nonatomic, copy) NSString *couple;
@property (nonatomic, copy) NSString *coupleWithHeart;
@property (nonatomic, copy) NSString *coupleWithHeartManMan;
@property (nonatomic, copy) NSString *coupleWithHeartWomanMan;
@property (nonatomic, copy) NSString *coupleWithHeartWomanWoman;
@property (nonatomic, copy) NSString *couplekissManMan;
@property (nonatomic, copy) NSString *couplekissManWoman;
@property (nonatomic, copy) NSString *couplekissWomanWoman;
@property (nonatomic, copy) NSString *cow;
@property (nonatomic, copy) NSString *cow2;
@property (nonatomic, copy) NSString *cowboyHatFace;
@property (nonatomic, copy) NSString *crab;
@property (nonatomic, copy) NSString *crayon;
@property (nonatomic, copy) NSString *creditCard;
@property (nonatomic, copy) NSString *crescentMoon;
@property (nonatomic, copy) NSString *cricket;
@property (nonatomic, copy) NSString *croatia;
@property (nonatomic, copy) NSString *crocodile;
@property (nonatomic, copy) NSString *croissant;
@property (nonatomic, copy) NSString *crossedFingers;
@property (nonatomic, copy) NSString *crossedFlags;
@property (nonatomic, copy) NSString *crossedSwords;
@property (nonatomic, copy) NSString *crown;
@property (nonatomic, copy) NSString *cry;
@property (nonatomic, copy) NSString *cryingCatFace;
@property (nonatomic, copy) NSString *crystalBall;
@property (nonatomic, copy) NSString *cuba;
@property (nonatomic, copy) NSString *cucumber;
@property (nonatomic, copy) NSString *cupid;
@property (nonatomic, copy) NSString *curacao;
@property (nonatomic, copy) NSString *curlyLoop;
@property (nonatomic, copy) NSString *currencyExchange;
@property (nonatomic, copy) NSString *curry;
@property (nonatomic, copy) NSString *custard;
@property (nonatomic, copy) NSString *customs;
@property (nonatomic, copy) NSString *cyclone;
@property (nonatomic, copy) NSString *cyprus;
@property (nonatomic, copy) NSString *czechRepublic;
@property (nonatomic, copy) NSString *dagger;
@property (nonatomic, copy) NSString *dancer;
@property (nonatomic, copy) NSString *dancers;
@property (nonatomic, copy) NSString *dancingMen;
@property (nonatomic, copy) NSString *dancingWomen;
@property (nonatomic, copy) NSString *dango;
@property (nonatomic, copy) NSString *darkSunglasses;
@property (nonatomic, copy) NSString *dart;
@property (nonatomic, copy) NSString *dash;
@property (nonatomic, copy) NSString *date;
@property (nonatomic, copy) NSString *de;
@property (nonatomic, copy) NSString *deciduousTree;
@property (nonatomic, copy) NSString *deer;
@property (nonatomic, copy) NSString *denmark;
@property (nonatomic, copy) NSString *departmentStore;
@property (nonatomic, copy) NSString *derelictHouse;
@property (nonatomic, copy) NSString *desert;
@property (nonatomic, copy) NSString *desertIsland;
@property (nonatomic, copy) NSString *desktopComputer;
@property (nonatomic, copy) NSString *detective;
@property (nonatomic, copy) NSString *diamondShapeWithADotInside;
@property (nonatomic, copy) NSString *diamonds;
@property (nonatomic, copy) NSString *disappointed;
@property (nonatomic, copy) NSString *disappointedRelieved;
@property (nonatomic, copy) NSString *dizzy;
@property (nonatomic, copy) NSString *dizzyFace;
@property (nonatomic, copy) NSString *djibouti;
@property (nonatomic, copy) NSString *doNotLitter;
@property (nonatomic, copy) NSString *dog;
@property (nonatomic, copy) NSString *dog2;
@property (nonatomic, copy) NSString *dollar;
@property (nonatomic, copy) NSString *dolls;
@property (nonatomic, copy) NSString *dolphin;
@property (nonatomic, copy) NSString *dominica;
@property (nonatomic, copy) NSString *dominicanRepublic;
@property (nonatomic, copy) NSString *door;
@property (nonatomic, copy) NSString *doughnut;
@property (nonatomic, copy) NSString *dove;
@property (nonatomic, copy) NSString *dragon;
@property (nonatomic, copy) NSString *dragonFace;
@property (nonatomic, copy) NSString *dress;
@property (nonatomic, copy) NSString *dromedaryCamel;
@property (nonatomic, copy) NSString *droolingFace;
@property (nonatomic, copy) NSString *droplet;
@property (nonatomic, copy) NSString *drum;
@property (nonatomic, copy) NSString *duck;
@property (nonatomic, copy) NSString *dvd;
@property (nonatomic, copy) NSString *eMail;
@property (nonatomic, copy) NSString *eagle;
@property (nonatomic, copy) NSString *ear;
@property (nonatomic, copy) NSString *earOfRice;
@property (nonatomic, copy) NSString *earthAfrica;
@property (nonatomic, copy) NSString *earthAmericas;
@property (nonatomic, copy) NSString *earthAsia;
@property (nonatomic, copy) NSString *ecuador;
@property (nonatomic, copy) NSString *egg;
@property (nonatomic, copy) NSString *eggplant;
@property (nonatomic, copy) NSString *egypt;
@property (nonatomic, copy) NSString *eight;
@property (nonatomic, copy) NSString *eightPointedBlackStar;
@property (nonatomic, copy) NSString *eightSpokedAsterisk;
@property (nonatomic, copy) NSString *elSalvador;
@property (nonatomic, copy) NSString *electricPlug;
@property (nonatomic, copy) NSString *electron;
@property (nonatomic, copy) NSString *elephant;
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *end;
@property (nonatomic, copy) NSString *envelope;
@property (nonatomic, copy) NSString *envelopeWithArrow;
@property (nonatomic, copy) NSString *equatorialGuinea;
@property (nonatomic, copy) NSString *eritrea;
@property (nonatomic, copy) NSString *es;
@property (nonatomic, copy) NSString *estonia;
@property (nonatomic, copy) NSString *ethiopia;
@property (nonatomic, copy) NSString *eu;
@property (nonatomic, copy) NSString *euro;
@property (nonatomic, copy) NSString *europeanCastle;
@property (nonatomic, copy) NSString *europeanPostOffice;
@property (nonatomic, copy) NSString *europeanUnion;
@property (nonatomic, copy) NSString *evergreenTree;
@property (nonatomic, copy) NSString *exclamation;
@property (nonatomic, copy) NSString *expressionless;
@property (nonatomic, copy) NSString *eye;
@property (nonatomic, copy) NSString *eyeSpeechBubble;
@property (nonatomic, copy) NSString *eyeglasses;
@property (nonatomic, copy) NSString *eyes;
@property (nonatomic, copy) NSString *faceWithHeadBandage;
@property (nonatomic, copy) NSString *faceWithThermometer;
@property (nonatomic, copy) NSString *facepunch;
@property (nonatomic, copy) NSString *factory;
@property (nonatomic, copy) NSString *falklandIslands;
@property (nonatomic, copy) NSString *fallenLeaf;
@property (nonatomic, copy) NSString *family;
@property (nonatomic, copy) NSString *familyManBoy;
@property (nonatomic, copy) NSString *familyManBoyBoy;
@property (nonatomic, copy) NSString *familyManGirl;
@property (nonatomic, copy) NSString *familyManGirlBoy;
@property (nonatomic, copy) NSString *familyManGirlGirl;
@property (nonatomic, copy) NSString *familyManManBoy;
@property (nonatomic, copy) NSString *familyManManBoyBoy;
@property (nonatomic, copy) NSString *familyManManGirl;
@property (nonatomic, copy) NSString *familyManManGirlBoy;
@property (nonatomic, copy) NSString *familyManManGirlGirl;
@property (nonatomic, copy) NSString *familyManWomanBoy;
@property (nonatomic, copy) NSString *familyManWomanBoyBoy;
@property (nonatomic, copy) NSString *familyManWomanGirl;
@property (nonatomic, copy) NSString *familyManWomanGirlBoy;
@property (nonatomic, copy) NSString *familyManWomanGirlGirl;
@property (nonatomic, copy) NSString *familyWomanBoy;
@property (nonatomic, copy) NSString *familyWomanBoyBoy;
@property (nonatomic, copy) NSString *familyWomanGirl;
@property (nonatomic, copy) NSString *familyWomanGirlBoy;
@property (nonatomic, copy) NSString *familyWomanGirlGirl;
@property (nonatomic, copy) NSString *familyWomanWomanBoy;
@property (nonatomic, copy) NSString *familyWomanWomanBoyBoy;
@property (nonatomic, copy) NSString *familyWomanWomanGirl;
@property (nonatomic, copy) NSString *familyWomanWomanGirlBoy;
@property (nonatomic, copy) NSString *familyWomanWomanGirlGirl;
@property (nonatomic, copy) NSString *faroeIslands;
@property (nonatomic, copy) NSString *fastForward;
@property (nonatomic, copy) NSString *fax;
@property (nonatomic, copy) NSString *fearful;
@property (nonatomic, copy) NSString *feelsgood;
@property (nonatomic, copy) NSString *feet;
@property (nonatomic, copy) NSString *femaleDetective;
@property (nonatomic, copy) NSString *ferrisWheel;
@property (nonatomic, copy) NSString *ferry;
@property (nonatomic, copy) NSString *fieldHockey;
@property (nonatomic, copy) NSString *fiji;
@property (nonatomic, copy) NSString *fileCabinet;
@property (nonatomic, copy) NSString *fileFolder;
@property (nonatomic, copy) NSString *filmProjector;
@property (nonatomic, copy) NSString *filmStrip;
@property (nonatomic, copy) NSString *finland;
@property (nonatomic, copy) NSString *finnadie;
@property (nonatomic, copy) NSString *fire;
@property (nonatomic, copy) NSString *fireEngine;
@property (nonatomic, copy) NSString *fireworks;
@property (nonatomic, copy) NSString *firstQuarterMoon;
@property (nonatomic, copy) NSString *firstQuarterMoonWithFace;
@property (nonatomic, copy) NSString *fish;
@property (nonatomic, copy) NSString *fishCake;
@property (nonatomic, copy) NSString *fishingPoleAndFish;
@property (nonatomic, copy) NSString *fist;
@property (nonatomic, copy) NSString *fistLeft;
@property (nonatomic, copy) NSString *fistOncoming;
@property (nonatomic, copy) NSString *fistRaised;
@property (nonatomic, copy) NSString *fistRight;
@property (nonatomic, copy) NSString *five;
@property (nonatomic, copy) NSString *flags;
@property (nonatomic, copy) NSString *flashlight;
@property (nonatomic, copy) NSString *fleurDeLis;
@property (nonatomic, copy) NSString *flightArrival;
@property (nonatomic, copy) NSString *flightDeparture;
@property (nonatomic, copy) NSString *flipper;
@property (nonatomic, copy) NSString *floppyDisk;
@property (nonatomic, copy) NSString *flowerPlayingCards;
@property (nonatomic, copy) NSString *flushed;
@property (nonatomic, copy) NSString *fog;
@property (nonatomic, copy) NSString *foggy;
@property (nonatomic, copy) NSString *football;
@property (nonatomic, copy) NSString *footprints;
@property (nonatomic, copy) NSString *forkAndKnife;
@property (nonatomic, copy) NSString *fountain;
@property (nonatomic, copy) NSString *fountainPen;
@property (nonatomic, copy) NSString *four;
@property (nonatomic, copy) NSString *fourLeafClover;
@property (nonatomic, copy) NSString *foxFace;
@property (nonatomic, copy) NSString *fr;
@property (nonatomic, copy) NSString *framedPicture;
@property (nonatomic, copy) NSString *free;
@property (nonatomic, copy) NSString *frenchGuiana;
@property (nonatomic, copy) NSString *frenchPolynesia;
@property (nonatomic, copy) NSString *frenchSouthernTerritories;
@property (nonatomic, copy) NSString *friedEgg;
@property (nonatomic, copy) NSString *friedShrimp;
@property (nonatomic, copy) NSString *fries;
@property (nonatomic, copy) NSString *frog;
@property (nonatomic, copy) NSString *frowning;
@property (nonatomic, copy) NSString *frowningFace;
@property (nonatomic, copy) NSString *frowningMan;
@property (nonatomic, copy) NSString *frowningWoman;
@property (nonatomic, copy) NSString *fu;
@property (nonatomic, copy) NSString *fuelpump;
@property (nonatomic, copy) NSString *fullMoon;
@property (nonatomic, copy) NSString *fullMoonWithFace;
@property (nonatomic, copy) NSString *funeralUrn;
@property (nonatomic, copy) NSString *gabon;
@property (nonatomic, copy) NSString *gambia;
@property (nonatomic, copy) NSString *gameDie;
@property (nonatomic, copy) NSString *gb;
@property (nonatomic, copy) NSString *gear;
@property (nonatomic, copy) NSString *gem;
@property (nonatomic, copy) NSString *gemini;
@property (nonatomic, copy) NSString *georgia;
@property (nonatomic, copy) NSString *ghana;
@property (nonatomic, copy) NSString *ghost;
@property (nonatomic, copy) NSString *gibraltar;
@property (nonatomic, copy) NSString *gift;
@property (nonatomic, copy) NSString *giftHeart;
@property (nonatomic, copy) NSString *girl;
@property (nonatomic, copy) NSString *globeWithMeridians;
@property (nonatomic, copy) NSString *goalNet;
@property (nonatomic, copy) NSString *goat;
@property (nonatomic, copy) NSString *goberserk;
@property (nonatomic, copy) NSString *godmode;
@property (nonatomic, copy) NSString *golf;
@property (nonatomic, copy) NSString *golfingMan;
@property (nonatomic, copy) NSString *golfingWoman;
@property (nonatomic, copy) NSString *gorilla;
@property (nonatomic, copy) NSString *grapes;
@property (nonatomic, copy) NSString *greece;
@property (nonatomic, copy) NSString *greenApple;
@property (nonatomic, copy) NSString *greenBook;
@property (nonatomic, copy) NSString *greenHeart;
@property (nonatomic, copy) NSString *greenSalad;
@property (nonatomic, copy) NSString *greenland;
@property (nonatomic, copy) NSString *grenada;
@property (nonatomic, copy) NSString *greyExclamation;
@property (nonatomic, copy) NSString *greyQuestion;
@property (nonatomic, copy) NSString *grimacing;
@property (nonatomic, copy) NSString *grin;
@property (nonatomic, copy) NSString *grinning;
@property (nonatomic, copy) NSString *guadeloupe;
@property (nonatomic, copy) NSString *guam;
@property (nonatomic, copy) NSString *guardsman;
@property (nonatomic, copy) NSString *guardswoman;
@property (nonatomic, copy) NSString *guatemala;
@property (nonatomic, copy) NSString *guernsey;
@property (nonatomic, copy) NSString *guinea;
@property (nonatomic, copy) NSString *guineaBissau;
@property (nonatomic, copy) NSString *guitar;
@property (nonatomic, copy) NSString *gun;
@property (nonatomic, copy) NSString *guyana;
@property (nonatomic, copy) NSString *haircut;
@property (nonatomic, copy) NSString *haircutMan;
@property (nonatomic, copy) NSString *haircutWoman;
@property (nonatomic, copy) NSString *haiti;
@property (nonatomic, copy) NSString *hamburger;
@property (nonatomic, copy) NSString *hammer;
@property (nonatomic, copy) NSString *hammerAndPick;
@property (nonatomic, copy) NSString *hammerAndWrench;
@property (nonatomic, copy) NSString *hamster;
@property (nonatomic, copy) NSString *hand;
@property (nonatomic, copy) NSString *handbag;
@property (nonatomic, copy) NSString *handshake;
@property (nonatomic, copy) NSString *hankey;
@property (nonatomic, copy) NSString *theHash;
@property (nonatomic, copy) NSString *hatchedChick;
@property (nonatomic, copy) NSString *hatchingChick;
@property (nonatomic, copy) NSString *headphones;
@property (nonatomic, copy) NSString *hearNoEvil;
@property (nonatomic, copy) NSString *heart;
@property (nonatomic, copy) NSString *heartDecoration;
@property (nonatomic, copy) NSString *heartEyes;
@property (nonatomic, copy) NSString *heartEyesCat;
@property (nonatomic, copy) NSString *heartbeat;
@property (nonatomic, copy) NSString *heartpulse;
@property (nonatomic, copy) NSString *hearts;
@property (nonatomic, copy) NSString *heavyCheckMark;
@property (nonatomic, copy) NSString *heavyDivisionSign;
@property (nonatomic, copy) NSString *heavyDollarSign;
@property (nonatomic, copy) NSString *heavyExclamationMark;
@property (nonatomic, copy) NSString *heavyHeartExclamation;
@property (nonatomic, copy) NSString *heavyMinusSign;
@property (nonatomic, copy) NSString *heavyMultiplicationX;
@property (nonatomic, copy) NSString *heavyPlusSign;
@property (nonatomic, copy) NSString *helicopter;
@property (nonatomic, copy) NSString *herb;
@property (nonatomic, copy) NSString *hibiscus;
@property (nonatomic, copy) NSString *highBrightness;
@property (nonatomic, copy) NSString *highHeel;
@property (nonatomic, copy) NSString *hocho;
@property (nonatomic, copy) NSString *hole;
@property (nonatomic, copy) NSString *honduras;
@property (nonatomic, copy) NSString *honeyPot;
@property (nonatomic, copy) NSString *honeybee;
@property (nonatomic, copy) NSString *hongKong;
@property (nonatomic, copy) NSString *horse;
@property (nonatomic, copy) NSString *horseRacing;
@property (nonatomic, copy) NSString *hospital;
@property (nonatomic, copy) NSString *hotPepper;
@property (nonatomic, copy) NSString *hotdog;
@property (nonatomic, copy) NSString *hotel;
@property (nonatomic, copy) NSString *hotsprings;
@property (nonatomic, copy) NSString *hourglass;
@property (nonatomic, copy) NSString *hourglassFlowingSand;
@property (nonatomic, copy) NSString *house;
@property (nonatomic, copy) NSString *houseWithGarden;
@property (nonatomic, copy) NSString *houses;
@property (nonatomic, copy) NSString *hugs;
@property (nonatomic, copy) NSString *hungary;
@property (nonatomic, copy) NSString *hurtrealbad;
@property (nonatomic, copy) NSString *hushed;
@property (nonatomic, copy) NSString *iceCream;
@property (nonatomic, copy) NSString *iceHockey;
@property (nonatomic, copy) NSString *iceSkate;
@property (nonatomic, copy) NSString *icecream;
@property (nonatomic, copy) NSString *iceland;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, copy) NSString *ideographAdvantage;
@property (nonatomic, copy) NSString *imp;
@property (nonatomic, copy) NSString *inboxTray;
@property (nonatomic, copy) NSString *incomingEnvelope;
@property (nonatomic, copy) NSString *india;
@property (nonatomic, copy) NSString *indonesia;
@property (nonatomic, copy) NSString *informationDeskPerson;
@property (nonatomic, copy) NSString *informationSource;
@property (nonatomic, copy) NSString *innocent;
@property (nonatomic, copy) NSString *interrobang;
@property (nonatomic, copy) NSString *iphone;
@property (nonatomic, copy) NSString *iran;
@property (nonatomic, copy) NSString *iraq;
@property (nonatomic, copy) NSString *ireland;
@property (nonatomic, copy) NSString *isleOfMan;
@property (nonatomic, copy) NSString *israel;
@property (nonatomic, copy) NSString *it;
@property (nonatomic, copy) NSString *izakayaLantern;
@property (nonatomic, copy) NSString *jackOLantern;
@property (nonatomic, copy) NSString *jamaica;
@property (nonatomic, copy) NSString *japan;
@property (nonatomic, copy) NSString *japaneseCastle;
@property (nonatomic, copy) NSString *japaneseGoblin;
@property (nonatomic, copy) NSString *japaneseOgre;
@property (nonatomic, copy) NSString *jeans;
@property (nonatomic, copy) NSString *jersey;
@property (nonatomic, copy) NSString *jordan;
@property (nonatomic, copy) NSString *joy;
@property (nonatomic, copy) NSString *joyCat;
@property (nonatomic, copy) NSString *joystick;
@property (nonatomic, copy) NSString *jp;
@property (nonatomic, copy) NSString *kaaba;
@property (nonatomic, copy) NSString *kazakhstan;
@property (nonatomic, copy) NSString *kenya;
@property (nonatomic, copy) NSString *key;
@property (nonatomic, copy) NSString *keyboard;
@property (nonatomic, copy) NSString *keycapTen;
@property (nonatomic, copy) NSString *kickScooter;
@property (nonatomic, copy) NSString *kimono;
@property (nonatomic, copy) NSString *kiribati;
@property (nonatomic, copy) NSString *kiss;
@property (nonatomic, copy) NSString *kissing;
@property (nonatomic, copy) NSString *kissingCat;
@property (nonatomic, copy) NSString *kissingClosedEyes;
@property (nonatomic, copy) NSString *kissingHeart;
@property (nonatomic, copy) NSString *kissingSmilingEyes;
@property (nonatomic, copy) NSString *kiwiFruit;
@property (nonatomic, copy) NSString *knife;
@property (nonatomic, copy) NSString *koala;
@property (nonatomic, copy) NSString *koko;
@property (nonatomic, copy) NSString *kosovo;
@property (nonatomic, copy) NSString *kr;
@property (nonatomic, copy) NSString *kuwait;
@property (nonatomic, copy) NSString *kyrgyzstan;
@property (nonatomic, copy) NSString *label;
@property (nonatomic, copy) NSString *lantern;
@property (nonatomic, copy) NSString *laos;
@property (nonatomic, copy) NSString *largeBlueCircle;
@property (nonatomic, copy) NSString *largeBlueDiamond;
@property (nonatomic, copy) NSString *largeOrangeDiamond;
@property (nonatomic, copy) NSString *lastQuarterMoon;
@property (nonatomic, copy) NSString *lastQuarterMoonWithFace;
@property (nonatomic, copy) NSString *latinCross;
@property (nonatomic, copy) NSString *latvia;
@property (nonatomic, copy) NSString *laughing;
@property (nonatomic, copy) NSString *leaves;
@property (nonatomic, copy) NSString *lebanon;
@property (nonatomic, copy) NSString *ledger;
@property (nonatomic, copy) NSString *leftLuggage;
@property (nonatomic, copy) NSString *leftRightArrow;
@property (nonatomic, copy) NSString *leftwardsArrowWithHook;
@property (nonatomic, copy) NSString *lemon;
@property (nonatomic, copy) NSString *leo;
@property (nonatomic, copy) NSString *leopard;
@property (nonatomic, copy) NSString *lesotho;
@property (nonatomic, copy) NSString *levelSlider;
@property (nonatomic, copy) NSString *liberia;
@property (nonatomic, copy) NSString *libra;
@property (nonatomic, copy) NSString *libya;
@property (nonatomic, copy) NSString *liechtenstein;
@property (nonatomic, copy) NSString *lightRail;
@property (nonatomic, copy) NSString *link;
@property (nonatomic, copy) NSString *lion;
@property (nonatomic, copy) NSString *lips;
@property (nonatomic, copy) NSString *lipstick;
@property (nonatomic, copy) NSString *lithuania;
@property (nonatomic, copy) NSString *lizard;
@property (nonatomic, copy) NSString *lock;
@property (nonatomic, copy) NSString *lockWithInkPen;
@property (nonatomic, copy) NSString *lollipop;
@property (nonatomic, copy) NSString *loop;
@property (nonatomic, copy) NSString *loudSound;
@property (nonatomic, copy) NSString *loudspeaker;
@property (nonatomic, copy) NSString *loveHotel;
@property (nonatomic, copy) NSString *loveLetter;
@property (nonatomic, copy) NSString *lowBrightness;
@property (nonatomic, copy) NSString *luxembourg;
@property (nonatomic, copy) NSString *lyingFace;
@property (nonatomic, copy) NSString *m;
@property (nonatomic, copy) NSString *macau;
@property (nonatomic, copy) NSString *macedonia;
@property (nonatomic, copy) NSString *madagascar;
@property (nonatomic, copy) NSString *mag;
@property (nonatomic, copy) NSString *magRight;
@property (nonatomic, copy) NSString *mahjong;
@property (nonatomic, copy) NSString *mailbox;
@property (nonatomic, copy) NSString *mailboxClosed;
@property (nonatomic, copy) NSString *mailboxWithMail;
@property (nonatomic, copy) NSString *mailboxWithNoMail;
@property (nonatomic, copy) NSString *malawi;
@property (nonatomic, copy) NSString *malaysia;
@property (nonatomic, copy) NSString *maldives;
@property (nonatomic, copy) NSString *maleDetective;
@property (nonatomic, copy) NSString *mali;
@property (nonatomic, copy) NSString *malta;
@property (nonatomic, copy) NSString *man;
@property (nonatomic, copy) NSString *manArtist;
@property (nonatomic, copy) NSString *manAstronaut;
@property (nonatomic, copy) NSString *manCartwheeling;
@property (nonatomic, copy) NSString *manCook;
@property (nonatomic, copy) NSString *manDancing;
@property (nonatomic, copy) NSString *manFacepalming;
@property (nonatomic, copy) NSString *manFactoryWorker;
@property (nonatomic, copy) NSString *manFarmer;
@property (nonatomic, copy) NSString *manFirefighter;
@property (nonatomic, copy) NSString *manHealthWorker;
@property (nonatomic, copy) NSString *manInTuxedo;
@property (nonatomic, copy) NSString *manJudge;
@property (nonatomic, copy) NSString *manJuggling;
@property (nonatomic, copy) NSString *manMechanic;
@property (nonatomic, copy) NSString *manOfficeWorker;
@property (nonatomic, copy) NSString *manPilot;
@property (nonatomic, copy) NSString *manPlayingHandball;
@property (nonatomic, copy) NSString *manPlayingWaterPolo;
@property (nonatomic, copy) NSString *manScientist;
@property (nonatomic, copy) NSString *manShrugging;
@property (nonatomic, copy) NSString *manSinger;
@property (nonatomic, copy) NSString *manStudent;
@property (nonatomic, copy) NSString *manTeacher;
@property (nonatomic, copy) NSString *manTechnologist;
@property (nonatomic, copy) NSString *manWithGuaPiMao;
@property (nonatomic, copy) NSString *manWithTurban;
@property (nonatomic, copy) NSString *mandarin;
@property (nonatomic, copy) NSString *mansShoe;
@property (nonatomic, copy) NSString *mantelpieceClock;
@property (nonatomic, copy) NSString *mapleLeaf;
@property (nonatomic, copy) NSString *marshallIslands;
@property (nonatomic, copy) NSString *martialArtsUniform;
@property (nonatomic, copy) NSString *martinique;
@property (nonatomic, copy) NSString *mask;
@property (nonatomic, copy) NSString *massage;
@property (nonatomic, copy) NSString *massageMan;
@property (nonatomic, copy) NSString *massageWoman;
@property (nonatomic, copy) NSString *mauritania;
@property (nonatomic, copy) NSString *mauritius;
@property (nonatomic, copy) NSString *mayotte;
@property (nonatomic, copy) NSString *meatOnBone;
@property (nonatomic, copy) NSString *medalMilitary;
@property (nonatomic, copy) NSString *medalSports;
@property (nonatomic, copy) NSString *mega;
@property (nonatomic, copy) NSString *melon;
@property (nonatomic, copy) NSString *memo;
@property (nonatomic, copy) NSString *menWrestling;
@property (nonatomic, copy) NSString *menorah;
@property (nonatomic, copy) NSString *mens;
@property (nonatomic, copy) NSString *metal;
@property (nonatomic, copy) NSString *metro;
@property (nonatomic, copy) NSString *mexico;
@property (nonatomic, copy) NSString *micronesia;
@property (nonatomic, copy) NSString *microphone;
@property (nonatomic, copy) NSString *microscope;
@property (nonatomic, copy) NSString *middleFinger;
@property (nonatomic, copy) NSString *milkGlass;
@property (nonatomic, copy) NSString *milkyWay;
@property (nonatomic, copy) NSString *minibus;
@property (nonatomic, copy) NSString *minidisc;
@property (nonatomic, copy) NSString *mobilePhoneOff;
@property (nonatomic, copy) NSString *moldova;
@property (nonatomic, copy) NSString *monaco;
@property (nonatomic, copy) NSString *moneyMouthFace;
@property (nonatomic, copy) NSString *moneyWithWings;
@property (nonatomic, copy) NSString *moneybag;
@property (nonatomic, copy) NSString *mongolia;
@property (nonatomic, copy) NSString *monkey;
@property (nonatomic, copy) NSString *monkeyFace;
@property (nonatomic, copy) NSString *monorail;
@property (nonatomic, copy) NSString *montenegro;
@property (nonatomic, copy) NSString *montserrat;
@property (nonatomic, copy) NSString *moon;
@property (nonatomic, copy) NSString *morocco;
@property (nonatomic, copy) NSString *mortarBoard;
@property (nonatomic, copy) NSString *mosque;
@property (nonatomic, copy) NSString *motorBoat;
@property (nonatomic, copy) NSString *motorScooter;
@property (nonatomic, copy) NSString *motorcycle;
@property (nonatomic, copy) NSString *motorway;
@property (nonatomic, copy) NSString *mountFuji;
@property (nonatomic, copy) NSString *mountain;
@property (nonatomic, copy) NSString *mountainBicyclist;
@property (nonatomic, copy) NSString *mountainBikingMan;
@property (nonatomic, copy) NSString *mountainBikingWoman;
@property (nonatomic, copy) NSString *mountainCableway;
@property (nonatomic, copy) NSString *mountainRailway;
@property (nonatomic, copy) NSString *mountainSnow;
@property (nonatomic, copy) NSString *mouse;
@property (nonatomic, copy) NSString *mouse2;
@property (nonatomic, copy) NSString *movieCamera;
@property (nonatomic, copy) NSString *moyai;
@property (nonatomic, copy) NSString *mozambique;
@property (nonatomic, copy) NSString *mrsClaus;
@property (nonatomic, copy) NSString *muscle;
@property (nonatomic, copy) NSString *mushroom;
@property (nonatomic, copy) NSString *musicalKeyboard;
@property (nonatomic, copy) NSString *musicalNote;
@property (nonatomic, copy) NSString *musicalScore;
@property (nonatomic, copy) NSString *mute;
@property (nonatomic, copy) NSString *myanmar;
@property (nonatomic, copy) NSString *nailCare;
@property (nonatomic, copy) NSString *nameBadge;
@property (nonatomic, copy) NSString *namibia;
@property (nonatomic, copy) NSString *nationalPark;
@property (nonatomic, copy) NSString *nauru;
@property (nonatomic, copy) NSString *nauseatedFace;
@property (nonatomic, copy) NSString *neckbeard;
@property (nonatomic, copy) NSString *necktie;
@property (nonatomic, copy) NSString *negativeSquaredCrossMark;
@property (nonatomic, copy) NSString *nepal;
@property (nonatomic, copy) NSString *nerdFace;
@property (nonatomic, copy) NSString *netherlands;
@property (nonatomic, copy) NSString *neutralFace;
@property (nonatomic, copy) NSString *theNew;
@property (nonatomic, copy) NSString *theNewCaledonia;
@property (nonatomic, copy) NSString *theNewMoon;
@property (nonatomic, copy) NSString *theNewMoonWithFace;
@property (nonatomic, copy) NSString *theNewZealand;
@property (nonatomic, copy) NSString *newspaper;
@property (nonatomic, copy) NSString *newspaperRoll;
@property (nonatomic, copy) NSString *nextTrackButton;
@property (nonatomic, copy) NSString *ng;
@property (nonatomic, copy) NSString *ngMan;
@property (nonatomic, copy) NSString *ngWoman;
@property (nonatomic, copy) NSString *nicaragua;
@property (nonatomic, copy) NSString *niger;
@property (nonatomic, copy) NSString *nigeria;
@property (nonatomic, copy) NSString *nightWithStars;
@property (nonatomic, copy) NSString *nine;
@property (nonatomic, copy) NSString *niue;
@property (nonatomic, copy) NSString *noBell;
@property (nonatomic, copy) NSString *noBicycles;
@property (nonatomic, copy) NSString *noEntry;
@property (nonatomic, copy) NSString *noEntrySign;
@property (nonatomic, copy) NSString *noGood;
@property (nonatomic, copy) NSString *noGoodMan;
@property (nonatomic, copy) NSString *noGoodWoman;
@property (nonatomic, copy) NSString *noMobilePhones;
@property (nonatomic, copy) NSString *noMouth;
@property (nonatomic, copy) NSString *noPedestrians;
@property (nonatomic, copy) NSString *noSmoking;
@property (nonatomic, copy) NSString *nonPotableWater;
@property (nonatomic, copy) NSString *norfolkIsland;
@property (nonatomic, copy) NSString *northKorea;
@property (nonatomic, copy) NSString *northernMarianaIslands;
@property (nonatomic, copy) NSString *norway;
@property (nonatomic, copy) NSString *nose;
@property (nonatomic, copy) NSString *notebook;
@property (nonatomic, copy) NSString *notebookWithDecorativeCover;
@property (nonatomic, copy) NSString *notes;
@property (nonatomic, copy) NSString *nutAndBolt;
@property (nonatomic, copy) NSString *o;
@property (nonatomic, copy) NSString *o2;
@property (nonatomic, copy) NSString *ocean;
@property (nonatomic, copy) NSString *octocat;
@property (nonatomic, copy) NSString *octopus;
@property (nonatomic, copy) NSString *oden;
@property (nonatomic, copy) NSString *office;
@property (nonatomic, copy) NSString *oilDrum;
@property (nonatomic, copy) NSString *ok;
@property (nonatomic, copy) NSString *okHand;
@property (nonatomic, copy) NSString *okMan;
@property (nonatomic, copy) NSString *okWoman;
@property (nonatomic, copy) NSString *oldKey;
@property (nonatomic, copy) NSString *olderMan;
@property (nonatomic, copy) NSString *olderWoman;
@property (nonatomic, copy) NSString *om;
@property (nonatomic, copy) NSString *oman;
@property (nonatomic, copy) NSString *on;
@property (nonatomic, copy) NSString *oncomingAutomobile;
@property (nonatomic, copy) NSString *oncomingBus;
@property (nonatomic, copy) NSString *oncomingPoliceCar;
@property (nonatomic, copy) NSString *oncomingTaxi;
@property (nonatomic, copy) NSString *one;
@property (nonatomic, copy) NSString *openBook;
@property (nonatomic, copy) NSString *openFileFolder;
@property (nonatomic, copy) NSString *openHands;
@property (nonatomic, copy) NSString *openMouth;
@property (nonatomic, copy) NSString *openUmbrella;
@property (nonatomic, copy) NSString *ophiuchus;
@property (nonatomic, copy) NSString *orange;
@property (nonatomic, copy) NSString *orangeBook;
@property (nonatomic, copy) NSString *orthodoxCross;
@property (nonatomic, copy) NSString *outboxTray;
@property (nonatomic, copy) NSString *owl;
@property (nonatomic, copy) NSString *ox;
@property (nonatomic, copy) NSString *package;
@property (nonatomic, copy) NSString *pageFacingUp;
@property (nonatomic, copy) NSString *pageWithCurl;
@property (nonatomic, copy) NSString *pager;
@property (nonatomic, copy) NSString *paintbrush;
@property (nonatomic, copy) NSString *pakistan;
@property (nonatomic, copy) NSString *palau;
@property (nonatomic, copy) NSString *palestinianTerritories;
@property (nonatomic, copy) NSString *palmTree;
@property (nonatomic, copy) NSString *panama;
@property (nonatomic, copy) NSString *pancakes;
@property (nonatomic, copy) NSString *pandaFace;
@property (nonatomic, copy) NSString *paperclip;
@property (nonatomic, copy) NSString *paperclips;
@property (nonatomic, copy) NSString *papuaNewGuinea;
@property (nonatomic, copy) NSString *paraguay;
@property (nonatomic, copy) NSString *parasolOnGround;
@property (nonatomic, copy) NSString *parking;
@property (nonatomic, copy) NSString *partAlternationMark;
@property (nonatomic, copy) NSString *partlySunny;
@property (nonatomic, copy) NSString *passengerShip;
@property (nonatomic, copy) NSString *passportControl;
@property (nonatomic, copy) NSString *pauseButton;
@property (nonatomic, copy) NSString *pawPrints;
@property (nonatomic, copy) NSString *peaceSymbol;
@property (nonatomic, copy) NSString *peach;
@property (nonatomic, copy) NSString *peanuts;
@property (nonatomic, copy) NSString *pear;
@property (nonatomic, copy) NSString *pen;
@property (nonatomic, copy) NSString *pencil;
@property (nonatomic, copy) NSString *pencil2;
@property (nonatomic, copy) NSString *penguin;
@property (nonatomic, copy) NSString *pensive;
@property (nonatomic, copy) NSString *performingArts;
@property (nonatomic, copy) NSString *persevere;
@property (nonatomic, copy) NSString *personFencing;
@property (nonatomic, copy) NSString *personFrowning;
@property (nonatomic, copy) NSString *personWithBlondHair;
@property (nonatomic, copy) NSString *personWithPoutingFace;
@property (nonatomic, copy) NSString *peru;
@property (nonatomic, copy) NSString *philippines;
@property (nonatomic, copy) NSString *phone;
@property (nonatomic, copy) NSString *pick;
@property (nonatomic, copy) NSString *pig;
@property (nonatomic, copy) NSString *pig2;
@property (nonatomic, copy) NSString *pigNose;
@property (nonatomic, copy) NSString *pill;
@property (nonatomic, copy) NSString *pineapple;
@property (nonatomic, copy) NSString *pingPong;
@property (nonatomic, copy) NSString *pisces;
@property (nonatomic, copy) NSString *pitcairnIslands;
@property (nonatomic, copy) NSString *pizza;
@property (nonatomic, copy) NSString *placeOfWorship;
@property (nonatomic, copy) NSString *plateWithCutlery;
@property (nonatomic, copy) NSString *playOrPauseButton;
@property (nonatomic, copy) NSString *pointDown;
@property (nonatomic, copy) NSString *pointLeft;
@property (nonatomic, copy) NSString *pointRight;
@property (nonatomic, copy) NSString *pointUp;
@property (nonatomic, copy) NSString *pointUp2;
@property (nonatomic, copy) NSString *poland;
@property (nonatomic, copy) NSString *policeCar;
@property (nonatomic, copy) NSString *policeman;
@property (nonatomic, copy) NSString *policewoman;
@property (nonatomic, copy) NSString *poodle;
@property (nonatomic, copy) NSString *poop;
@property (nonatomic, copy) NSString *popcorn;
@property (nonatomic, copy) NSString *portugal;
@property (nonatomic, copy) NSString *postOffice;
@property (nonatomic, copy) NSString *postalHorn;
@property (nonatomic, copy) NSString *postbox;
@property (nonatomic, copy) NSString *potableWater;
@property (nonatomic, copy) NSString *potato;
@property (nonatomic, copy) NSString *pouch;
@property (nonatomic, copy) NSString *poultryLeg;
@property (nonatomic, copy) NSString *pound;
@property (nonatomic, copy) NSString *pout;
@property (nonatomic, copy) NSString *poutingCat;
@property (nonatomic, copy) NSString *poutingMan;
@property (nonatomic, copy) NSString *poutingWoman;
@property (nonatomic, copy) NSString *pray;
@property (nonatomic, copy) NSString *prayerBeads;
@property (nonatomic, copy) NSString *pregnantWoman;
@property (nonatomic, copy) NSString *previousTrackButton;
@property (nonatomic, copy) NSString *prince;
@property (nonatomic, copy) NSString *princess;
@property (nonatomic, copy) NSString *printer;
@property (nonatomic, copy) NSString *puertoRico;
@property (nonatomic, copy) NSString *punch;
@property (nonatomic, copy) NSString *purpleHeart;
@property (nonatomic, copy) NSString *purse;
@property (nonatomic, copy) NSString *pushpin;
@property (nonatomic, copy) NSString *putLitterInItsPlace;
@property (nonatomic, copy) NSString *qatar;
@property (nonatomic, copy) NSString *question;
@property (nonatomic, copy) NSString *rabbit;
@property (nonatomic, copy) NSString *rabbit2;
@property (nonatomic, copy) NSString *racehorse;
@property (nonatomic, copy) NSString *racingCar;
@property (nonatomic, copy) NSString *radio;
@property (nonatomic, copy) NSString *radioButton;
@property (nonatomic, copy) NSString *radioactive;
@property (nonatomic, copy) NSString *rage;
@property (nonatomic, copy) NSString *rage1;
@property (nonatomic, copy) NSString *rage2;
@property (nonatomic, copy) NSString *rage3;
@property (nonatomic, copy) NSString *rage4;
@property (nonatomic, copy) NSString *railwayCar;
@property (nonatomic, copy) NSString *railwayTrack;
@property (nonatomic, copy) NSString *rainbow;
@property (nonatomic, copy) NSString *rainbowFlag;
@property (nonatomic, copy) NSString *raisedBackOfHand;
@property (nonatomic, copy) NSString *raisedHand;
@property (nonatomic, copy) NSString *raisedHandWithFingersSplayed;
@property (nonatomic, copy) NSString *raisedHands;
@property (nonatomic, copy) NSString *raisingHand;
@property (nonatomic, copy) NSString *raisingHandMan;
@property (nonatomic, copy) NSString *raisingHandWoman;
@property (nonatomic, copy) NSString *ram;
@property (nonatomic, copy) NSString *ramen;
@property (nonatomic, copy) NSString *rat;
@property (nonatomic, copy) NSString *recordButton;
@property (nonatomic, copy) NSString *recycle;
@property (nonatomic, copy) NSString *redCar;
@property (nonatomic, copy) NSString *redCircle;
@property (nonatomic, copy) NSString *registered;
@property (nonatomic, copy) NSString *relaxed;
@property (nonatomic, copy) NSString *relieved;
@property (nonatomic, copy) NSString *reminderRibbon;
@property (nonatomic, copy) NSString *repeat;
@property (nonatomic, copy) NSString *repeatOne;
@property (nonatomic, copy) NSString *rescueWorkerHelmet;
@property (nonatomic, copy) NSString *restroom;
@property (nonatomic, copy) NSString *reunion;
@property (nonatomic, copy) NSString *revolvingHearts;
@property (nonatomic, copy) NSString *rewind;
@property (nonatomic, copy) NSString *rhinoceros;
@property (nonatomic, copy) NSString *ribbon;
@property (nonatomic, copy) NSString *rice;
@property (nonatomic, copy) NSString *riceBall;
@property (nonatomic, copy) NSString *riceCracker;
@property (nonatomic, copy) NSString *riceScene;
@property (nonatomic, copy) NSString *rightAngerBubble;
@property (nonatomic, copy) NSString *ring;
@property (nonatomic, copy) NSString *robot;
@property (nonatomic, copy) NSString *rocket;
@property (nonatomic, copy) NSString *rofl;
@property (nonatomic, copy) NSString *rollEyes;
@property (nonatomic, copy) NSString *rollerCoaster;
@property (nonatomic, copy) NSString *romania;
@property (nonatomic, copy) NSString *rooster;
@property (nonatomic, copy) NSString *rose;
@property (nonatomic, copy) NSString *rosette;
@property (nonatomic, copy) NSString *rotatingLight;
@property (nonatomic, copy) NSString *roundPushpin;
@property (nonatomic, copy) NSString *rowboat;
@property (nonatomic, copy) NSString *rowingMan;
@property (nonatomic, copy) NSString *rowingWoman;
@property (nonatomic, copy) NSString *ru;
@property (nonatomic, copy) NSString *rugbyFootball;
@property (nonatomic, copy) NSString *runner;
@property (nonatomic, copy) NSString *running;
@property (nonatomic, copy) NSString *runningMan;
@property (nonatomic, copy) NSString *runningShirtWithSash;
@property (nonatomic, copy) NSString *runningWoman;
@property (nonatomic, copy) NSString *rwanda;
@property (nonatomic, copy) NSString *sa;
@property (nonatomic, copy) NSString *sagittarius;
@property (nonatomic, copy) NSString *sailboat;
@property (nonatomic, copy) NSString *sake;
@property (nonatomic, copy) NSString *samoa;
@property (nonatomic, copy) NSString *sanMarino;
@property (nonatomic, copy) NSString *sandal;
@property (nonatomic, copy) NSString *santa;
@property (nonatomic, copy) NSString *saoTomePrincipe;
@property (nonatomic, copy) NSString *satellite;
@property (nonatomic, copy) NSString *satisfied;
@property (nonatomic, copy) NSString *saudiArabia;
@property (nonatomic, copy) NSString *saxophone;
@property (nonatomic, copy) NSString *school;
@property (nonatomic, copy) NSString *schoolSatchel;
@property (nonatomic, copy) NSString *scissors;
@property (nonatomic, copy) NSString *scorpion;
@property (nonatomic, copy) NSString *scorpius;
@property (nonatomic, copy) NSString *scream;
@property (nonatomic, copy) NSString *screamCat;
@property (nonatomic, copy) NSString *scroll;
@property (nonatomic, copy) NSString *seat;
@property (nonatomic, copy) NSString *secret;
@property (nonatomic, copy) NSString *seeNoEvil;
@property (nonatomic, copy) NSString *seedling;
@property (nonatomic, copy) NSString *selfie;
@property (nonatomic, copy) NSString *senegal;
@property (nonatomic, copy) NSString *serbia;
@property (nonatomic, copy) NSString *seven;
@property (nonatomic, copy) NSString *seychelles;
@property (nonatomic, copy) NSString *shallowPanOfFood;
@property (nonatomic, copy) NSString *shamrock;
@property (nonatomic, copy) NSString *shark;
@property (nonatomic, copy) NSString *shavedIce;
@property (nonatomic, copy) NSString *sheep;
@property (nonatomic, copy) NSString *shell;
@property (nonatomic, copy) NSString *shield;
@property (nonatomic, copy) NSString *shintoShrine;
@property (nonatomic, copy) NSString *ship;
@property (nonatomic, copy) NSString *shipit;
@property (nonatomic, copy) NSString *shirt;
@property (nonatomic, copy) NSString *shit;
@property (nonatomic, copy) NSString *shoe;
@property (nonatomic, copy) NSString *shopping;
@property (nonatomic, copy) NSString *shoppingCart;
@property (nonatomic, copy) NSString *shower;
@property (nonatomic, copy) NSString *shrimp;
@property (nonatomic, copy) NSString *sierraLeone;
@property (nonatomic, copy) NSString *signalStrength;
@property (nonatomic, copy) NSString *singapore;
@property (nonatomic, copy) NSString *sintMaarten;
@property (nonatomic, copy) NSString *six;
@property (nonatomic, copy) NSString *sixPointedStar;
@property (nonatomic, copy) NSString *ski;
@property (nonatomic, copy) NSString *skier;
@property (nonatomic, copy) NSString *skull;
@property (nonatomic, copy) NSString *skullAndCrossbones;
@property (nonatomic, copy) NSString *sleeping;
@property (nonatomic, copy) NSString *sleepingBed;
@property (nonatomic, copy) NSString *sleepy;
@property (nonatomic, copy) NSString *slightlyFrowningFace;
@property (nonatomic, copy) NSString *slightlySmilingFace;
@property (nonatomic, copy) NSString *slotMachine;
@property (nonatomic, copy) NSString *slovakia;
@property (nonatomic, copy) NSString *slovenia;
@property (nonatomic, copy) NSString *smallAirplane;
@property (nonatomic, copy) NSString *smallBlueDiamond;
@property (nonatomic, copy) NSString *smallOrangeDiamond;
@property (nonatomic, copy) NSString *smallRedTriangle;
@property (nonatomic, copy) NSString *smallRedTriangleDown;
@property (nonatomic, copy) NSString *smile;
@property (nonatomic, copy) NSString *smileCat;
@property (nonatomic, copy) NSString *smiley;
@property (nonatomic, copy) NSString *smileyCat;
@property (nonatomic, copy) NSString *smilingImp;
@property (nonatomic, copy) NSString *smirk;
@property (nonatomic, copy) NSString *smirkCat;
@property (nonatomic, copy) NSString *smoking;
@property (nonatomic, copy) NSString *snail;
@property (nonatomic, copy) NSString *snake;
@property (nonatomic, copy) NSString *sneezingFace;
@property (nonatomic, copy) NSString *snowboarder;
@property (nonatomic, copy) NSString *snowflake;
@property (nonatomic, copy) NSString *snowman;
@property (nonatomic, copy) NSString *snowmanWithSnow;
@property (nonatomic, copy) NSString *sob;
@property (nonatomic, copy) NSString *soccer;
@property (nonatomic, copy) NSString *solomonIslands;
@property (nonatomic, copy) NSString *somalia;
@property (nonatomic, copy) NSString *soon;
@property (nonatomic, copy) NSString *sos;
@property (nonatomic, copy) NSString *sound;
@property (nonatomic, copy) NSString *southAfrica;
@property (nonatomic, copy) NSString *southGeorgiaSouthSandwichIslands;
@property (nonatomic, copy) NSString *southSudan;
@property (nonatomic, copy) NSString *spaceInvader;
@property (nonatomic, copy) NSString *spades;
@property (nonatomic, copy) NSString *spaghetti;
@property (nonatomic, copy) NSString *sparkle;
@property (nonatomic, copy) NSString *sparkler;
@property (nonatomic, copy) NSString *sparkles;
@property (nonatomic, copy) NSString *sparklingHeart;
@property (nonatomic, copy) NSString *speakNoEvil;
@property (nonatomic, copy) NSString *speaker;
@property (nonatomic, copy) NSString *speakingHead;
@property (nonatomic, copy) NSString *speechBalloon;
@property (nonatomic, copy) NSString *speedboat;
@property (nonatomic, copy) NSString *spider;
@property (nonatomic, copy) NSString *spiderWeb;
@property (nonatomic, copy) NSString *spiralCalendar;
@property (nonatomic, copy) NSString *spiralNotepad;
@property (nonatomic, copy) NSString *spoon;
@property (nonatomic, copy) NSString *squid;
@property (nonatomic, copy) NSString *squirrel;
@property (nonatomic, copy) NSString *sriLanka;
@property (nonatomic, copy) NSString *stBarthelemy;
@property (nonatomic, copy) NSString *stHelena;
@property (nonatomic, copy) NSString *stKittsNevis;
@property (nonatomic, copy) NSString *stLucia;
@property (nonatomic, copy) NSString *stPierreMiquelon;
@property (nonatomic, copy) NSString *stVincentGrenadines;
@property (nonatomic, copy) NSString *stadium;
@property (nonatomic, copy) NSString *star;
@property (nonatomic, copy) NSString *star2;
@property (nonatomic, copy) NSString *starAndCrescent;
@property (nonatomic, copy) NSString *starOfDavid;
@property (nonatomic, copy) NSString *stars;
@property (nonatomic, copy) NSString *station;
@property (nonatomic, copy) NSString *statueOfLiberty;
@property (nonatomic, copy) NSString *steamLocomotive;
@property (nonatomic, copy) NSString *stew;
@property (nonatomic, copy) NSString *stopButton;
@property (nonatomic, copy) NSString *stopSign;
@property (nonatomic, copy) NSString *stopwatch;
@property (nonatomic, copy) NSString *straightRuler;
@property (nonatomic, copy) NSString *strawberry;
@property (nonatomic, copy) NSString *stuckOutTongue;
@property (nonatomic, copy) NSString *stuckOutTongueClosedEyes;
@property (nonatomic, copy) NSString *stuckOutTongueWinkingEye;
@property (nonatomic, copy) NSString *studioMicrophone;
@property (nonatomic, copy) NSString *stuffedFlatbread;
@property (nonatomic, copy) NSString *sudan;
@property (nonatomic, copy) NSString *sunBehindLargeCloud;
@property (nonatomic, copy) NSString *sunBehindRainCloud;
@property (nonatomic, copy) NSString *sunBehindSmallCloud;
@property (nonatomic, copy) NSString *sunWithFace;
@property (nonatomic, copy) NSString *sunflower;
@property (nonatomic, copy) NSString *sunglasses;
@property (nonatomic, copy) NSString *sunny;
@property (nonatomic, copy) NSString *sunrise;
@property (nonatomic, copy) NSString *sunriseOverMountains;
@property (nonatomic, copy) NSString *surfer;
@property (nonatomic, copy) NSString *surfingMan;
@property (nonatomic, copy) NSString *surfingWoman;
@property (nonatomic, copy) NSString *suriname;
@property (nonatomic, copy) NSString *sushi;
@property (nonatomic, copy) NSString *suspect;
@property (nonatomic, copy) NSString *suspensionRailway;
@property (nonatomic, copy) NSString *swaziland;
@property (nonatomic, copy) NSString *sweat;
@property (nonatomic, copy) NSString *sweatDrops;
@property (nonatomic, copy) NSString *sweatSmile;
@property (nonatomic, copy) NSString *sweden;
@property (nonatomic, copy) NSString *sweetPotato;
@property (nonatomic, copy) NSString *swimmer;
@property (nonatomic, copy) NSString *swimmingMan;
@property (nonatomic, copy) NSString *swimmingWoman;
@property (nonatomic, copy) NSString *switzerland;
@property (nonatomic, copy) NSString *symbols;
@property (nonatomic, copy) NSString *synagogue;
@property (nonatomic, copy) NSString *syria;
@property (nonatomic, copy) NSString *syringe;
@property (nonatomic, copy) NSString *taco;
@property (nonatomic, copy) NSString *tada;
@property (nonatomic, copy) NSString *taiwan;
@property (nonatomic, copy) NSString *tajikistan;
@property (nonatomic, copy) NSString *tanabataTree;
@property (nonatomic, copy) NSString *tangerine;
@property (nonatomic, copy) NSString *tanzania;
@property (nonatomic, copy) NSString *taurus;
@property (nonatomic, copy) NSString *taxi;
@property (nonatomic, copy) NSString *tea;
@property (nonatomic, copy) NSString *telephone;
@property (nonatomic, copy) NSString *telephoneReceiver;
@property (nonatomic, copy) NSString *telescope;
@property (nonatomic, copy) NSString *tennis;
@property (nonatomic, copy) NSString *tent;
@property (nonatomic, copy) NSString *thailand;
@property (nonatomic, copy) NSString *thermometer;
@property (nonatomic, copy) NSString *thinking;
@property (nonatomic, copy) NSString *thoughtBalloon;
@property (nonatomic, copy) NSString *three;
@property (nonatomic, copy) NSString *thumbsdown;
@property (nonatomic, copy) NSString *thumbsup;
@property (nonatomic, copy) NSString *ticket;
@property (nonatomic, copy) NSString *tickets;
@property (nonatomic, copy) NSString *tiger;
@property (nonatomic, copy) NSString *tiger2;
@property (nonatomic, copy) NSString *timerClock;
@property (nonatomic, copy) NSString *timorLeste;
@property (nonatomic, copy) NSString *tippingHandMan;
@property (nonatomic, copy) NSString *tippingHandWoman;
@property (nonatomic, copy) NSString *tiredFace;
@property (nonatomic, copy) NSString *tm;
@property (nonatomic, copy) NSString *togo;
@property (nonatomic, copy) NSString *toilet;
@property (nonatomic, copy) NSString *tokelau;
@property (nonatomic, copy) NSString *tokyoTower;
@property (nonatomic, copy) NSString *tomato;
@property (nonatomic, copy) NSString *tonga;
@property (nonatomic, copy) NSString *tongue;
@property (nonatomic, copy) NSString *top;
@property (nonatomic, copy) NSString *tophat;
@property (nonatomic, copy) NSString *tornado;
@property (nonatomic, copy) NSString *tr;
@property (nonatomic, copy) NSString *trackball;
@property (nonatomic, copy) NSString *tractor;
@property (nonatomic, copy) NSString *trafficLight;
@property (nonatomic, copy) NSString *train;
@property (nonatomic, copy) NSString *train2;
@property (nonatomic, copy) NSString *tram;
@property (nonatomic, copy) NSString *triangularFlagOnPost;
@property (nonatomic, copy) NSString *triangularRuler;
@property (nonatomic, copy) NSString *trident;
@property (nonatomic, copy) NSString *trinidadTobago;
@property (nonatomic, copy) NSString *triumph;
@property (nonatomic, copy) NSString *trolleybus;
@property (nonatomic, copy) NSString *trollface;
@property (nonatomic, copy) NSString *trophy;
@property (nonatomic, copy) NSString *tropicalDrink;
@property (nonatomic, copy) NSString *tropicalFish;
@property (nonatomic, copy) NSString *truck;
@property (nonatomic, copy) NSString *trumpet;
@property (nonatomic, copy) NSString *tshirt;
@property (nonatomic, copy) NSString *tulip;
@property (nonatomic, copy) NSString *tumblerGlass;
@property (nonatomic, copy) NSString *tunisia;
@property (nonatomic, copy) NSString *turkey;
@property (nonatomic, copy) NSString *turkmenistan;
@property (nonatomic, copy) NSString *turksCaicosIslands;
@property (nonatomic, copy) NSString *turtle;
@property (nonatomic, copy) NSString *tuvalu;
@property (nonatomic, copy) NSString *tv;
@property (nonatomic, copy) NSString *twistedRightwardsArrows;
@property (nonatomic, copy) NSString *two;
@property (nonatomic, copy) NSString *twoHearts;
@property (nonatomic, copy) NSString *twoMenHoldingHands;
@property (nonatomic, copy) NSString *twoWomenHoldingHands;
@property (nonatomic, copy) NSString *u5272;
@property (nonatomic, copy) NSString *u5408;
@property (nonatomic, copy) NSString *u55B6;
@property (nonatomic, copy) NSString *u6307;
@property (nonatomic, copy) NSString *u6708;
@property (nonatomic, copy) NSString *u6709;
@property (nonatomic, copy) NSString *u6E80;
@property (nonatomic, copy) NSString *u7121;
@property (nonatomic, copy) NSString *u7533;
@property (nonatomic, copy) NSString *u7981;
@property (nonatomic, copy) NSString *u7A7A;
@property (nonatomic, copy) NSString *uganda;
@property (nonatomic, copy) NSString *uk;
@property (nonatomic, copy) NSString *ukraine;
@property (nonatomic, copy) NSString *umbrella;
@property (nonatomic, copy) NSString *unamused;
@property (nonatomic, copy) NSString *underage;
@property (nonatomic, copy) NSString *unicorn;
@property (nonatomic, copy) NSString *unitedArabEmirates;
@property (nonatomic, copy) NSString *unlock;
@property (nonatomic, copy) NSString *up;
@property (nonatomic, copy) NSString *upsideDownFace;
@property (nonatomic, copy) NSString *uruguay;
@property (nonatomic, copy) NSString *us;
@property (nonatomic, copy) NSString *usVirginIslands;
@property (nonatomic, copy) NSString *uzbekistan;
@property (nonatomic, copy) NSString *v;
@property (nonatomic, copy) NSString *vanuatu;
@property (nonatomic, copy) NSString *vaticanCity;
@property (nonatomic, copy) NSString *venezuela;
@property (nonatomic, copy) NSString *verticalTrafficLight;
@property (nonatomic, copy) NSString *vhs;
@property (nonatomic, copy) NSString *vibrationMode;
@property (nonatomic, copy) NSString *videoCamera;
@property (nonatomic, copy) NSString *videoGame;
@property (nonatomic, copy) NSString *vietnam;
@property (nonatomic, copy) NSString *violin;
@property (nonatomic, copy) NSString *virgo;
@property (nonatomic, copy) NSString *volcano;
@property (nonatomic, copy) NSString *volleyball;
@property (nonatomic, copy) NSString *vs;
@property (nonatomic, copy) NSString *vulcanSalute;
@property (nonatomic, copy) NSString *walking;
@property (nonatomic, copy) NSString *walkingMan;
@property (nonatomic, copy) NSString *walkingWoman;
@property (nonatomic, copy) NSString *wallisFutuna;
@property (nonatomic, copy) NSString *waningCrescentMoon;
@property (nonatomic, copy) NSString *waningGibbousMoon;
@property (nonatomic, copy) NSString *warning;
@property (nonatomic, copy) NSString *wastebasket;
@property (nonatomic, copy) NSString *watch;
@property (nonatomic, copy) NSString *waterBuffalo;
@property (nonatomic, copy) NSString *watermelon;
@property (nonatomic, copy) NSString *wave;
@property (nonatomic, copy) NSString *wavyDash;
@property (nonatomic, copy) NSString *waxingCrescentMoon;
@property (nonatomic, copy) NSString *waxingGibbousMoon;
@property (nonatomic, copy) NSString *wc;
@property (nonatomic, copy) NSString *weary;
@property (nonatomic, copy) NSString *wedding;
@property (nonatomic, copy) NSString *weightLiftingMan;
@property (nonatomic, copy) NSString *weightLiftingWoman;
@property (nonatomic, copy) NSString *westernSahara;
@property (nonatomic, copy) NSString *whale;
@property (nonatomic, copy) NSString *whale2;
@property (nonatomic, copy) NSString *wheelOfDharma;
@property (nonatomic, copy) NSString *wheelchair;
@property (nonatomic, copy) NSString *whiteCheckMark;
@property (nonatomic, copy) NSString *whiteCircle;
@property (nonatomic, copy) NSString *whiteFlag;
@property (nonatomic, copy) NSString *whiteFlower;
@property (nonatomic, copy) NSString *whiteLargeSquare;
@property (nonatomic, copy) NSString *whiteMediumSmallSquare;
@property (nonatomic, copy) NSString *whiteMediumSquare;
@property (nonatomic, copy) NSString *whiteSmallSquare;
@property (nonatomic, copy) NSString *whiteSquareButton;
@property (nonatomic, copy) NSString *wiltedFlower;
@property (nonatomic, copy) NSString *windChime;
@property (nonatomic, copy) NSString *windFace;
@property (nonatomic, copy) NSString *wineGlass;
@property (nonatomic, copy) NSString *wink;
@property (nonatomic, copy) NSString *wolf;
@property (nonatomic, copy) NSString *woman;
@property (nonatomic, copy) NSString *womanArtist;
@property (nonatomic, copy) NSString *womanAstronaut;
@property (nonatomic, copy) NSString *womanCartwheeling;
@property (nonatomic, copy) NSString *womanCook;
@property (nonatomic, copy) NSString *womanFacepalming;
@property (nonatomic, copy) NSString *womanFactoryWorker;
@property (nonatomic, copy) NSString *womanFarmer;
@property (nonatomic, copy) NSString *womanFirefighter;
@property (nonatomic, copy) NSString *womanHealthWorker;
@property (nonatomic, copy) NSString *womanJudge;
@property (nonatomic, copy) NSString *womanJuggling;
@property (nonatomic, copy) NSString *womanMechanic;
@property (nonatomic, copy) NSString *womanOfficeWorker;
@property (nonatomic, copy) NSString *womanPilot;
@property (nonatomic, copy) NSString *womanPlayingHandball;
@property (nonatomic, copy) NSString *womanPlayingWaterPolo;
@property (nonatomic, copy) NSString *womanScientist;
@property (nonatomic, copy) NSString *womanShrugging;
@property (nonatomic, copy) NSString *womanSinger;
@property (nonatomic, copy) NSString *womanStudent;
@property (nonatomic, copy) NSString *womanTeacher;
@property (nonatomic, copy) NSString *womanTechnologist;
@property (nonatomic, copy) NSString *womanWithTurban;
@property (nonatomic, copy) NSString *womansClothes;
@property (nonatomic, copy) NSString *womansHat;
@property (nonatomic, copy) NSString *womenWrestling;
@property (nonatomic, copy) NSString *womens;
@property (nonatomic, copy) NSString *worldMap;
@property (nonatomic, copy) NSString *worried;
@property (nonatomic, copy) NSString *wrench;
@property (nonatomic, copy) NSString *writingHand;
@property (nonatomic, copy) NSString *x;
@property (nonatomic, copy) NSString *yellowHeart;
@property (nonatomic, copy) NSString *yemen;
@property (nonatomic, copy) NSString *yen;
@property (nonatomic, copy) NSString *yinYang;
@property (nonatomic, copy) NSString *yum;
@property (nonatomic, copy) NSString *zambia;
@property (nonatomic, copy) NSString *zap;
@property (nonatomic, copy) NSString *zero;
@property (nonatomic, copy) NSString *zimbabwe;
@property (nonatomic, copy) NSString *zipperMouthFace;
@property (nonatomic, copy) NSString *zzz;

+ (_Nullable instancetype)fromJSON:(NSString *)json encoding:(NSStringEncoding)encoding error:(NSError *_Nullable *)error;
+ (_Nullable instancetype)fromData:(NSData *)data error:(NSError *_Nullable *)error;
- (NSString *_Nullable)toJSON:(NSStringEncoding)encoding error:(NSError *_Nullable *)error;
- (NSData *_Nullable)toData:(NSError *_Nullable *)error;
@end

@interface APIEvent : NSObject
@property (nonatomic, copy)             NSString *identifier;
@property (nonatomic, copy)             NSString *type;
@property (nonatomic, strong)           APIActor *actor;
@property (nonatomic, strong)           APIRepo *repo;
@property (nonatomic, strong)           APIPayload *payload;
@property (nonatomic, assign)           BOOL isPublic;
@property (nonatomic, copy)             NSString *createdAt;
@property (nonatomic, nullable, strong) APIActor *org;
@end

@interface APIActor : NSObject
@property (nonatomic, assign)         NSInteger identifier;
@property (nonatomic, copy)           NSString *login;
@property (nonatomic, nullable, copy) NSString *displayLogin;
@property (nonatomic, assign)         APIGravatarID *gravatarID;
@property (nonatomic, copy)           NSString *url;
@property (nonatomic, copy)           NSString *avatarURL;
@end

@interface APIPayload : NSObject
@property (nonatomic, nullable, strong) NSNumber *pushID;
@property (nonatomic, nullable, strong) NSNumber *size;
@property (nonatomic, nullable, strong) NSNumber *distinctSize;
@property (nonatomic, nullable, copy)   NSString *ref;
@property (nonatomic, nullable, copy)   NSString *head;
@property (nonatomic, nullable, copy)   NSString *before;
@property (nonatomic, nullable, copy)   NSArray<APICommit *> *commits;
@property (nonatomic, nullable, strong) APIForkee *forkee;
@property (nonatomic, nullable, copy)   NSString *action;
@property (nonatomic, nullable, strong) NSNumber *number;
@property (nonatomic, nullable, strong) APIPullRequest *pullRequest;
@property (nonatomic, nullable, copy)   NSString *refType;
@property (nonatomic, nullable, copy)   NSString *masterBranch;
@property (nonatomic, nullable, copy)   NSString *theDescription;
@property (nonatomic, nullable, copy)   NSString *pusherType;
@property (nonatomic, nullable, strong) APIIssue *issue;
@property (nonatomic, nullable, strong) APIComment *comment;
@end

@interface APIComment : NSObject
@property (nonatomic, copy)   NSString *url;
@property (nonatomic, copy)   NSString *htmlURL;
@property (nonatomic, copy)   NSString *issueURL;
@property (nonatomic, assign) NSInteger identifier;
@property (nonatomic, strong) APIUser *user;
@property (nonatomic, copy)   NSString *createdAt;
@property (nonatomic, copy)   NSString *updatedAt;
@property (nonatomic, copy)   NSString *authorAssociation;
@property (nonatomic, copy)   NSString *body;
@end

@interface APIUser : NSObject
@property (nonatomic, copy)   NSString *login;
@property (nonatomic, assign) NSInteger identifier;
@property (nonatomic, copy)   NSString *avatarURL;
@property (nonatomic, assign) APIGravatarID *gravatarID;
@property (nonatomic, copy)   NSString *url;
@property (nonatomic, copy)   NSString *htmlURL;
@property (nonatomic, copy)   NSString *followersURL;
@property (nonatomic, copy)   NSString *followingURL;
@property (nonatomic, copy)   NSString *gistsURL;
@property (nonatomic, copy)   NSString *starredURL;
@property (nonatomic, copy)   NSString *subscriptionsURL;
@property (nonatomic, copy)   NSString *organizationsURL;
@property (nonatomic, copy)   NSString *reposURL;
@property (nonatomic, copy)   NSString *eventsURL;
@property (nonatomic, copy)   NSString *receivedEventsURL;
@property (nonatomic, assign) APIUserType *type;
@property (nonatomic, assign) BOOL isSiteAdmin;
@end

@interface APICommit : NSObject
@property (nonatomic, copy)   NSString *sha;
@property (nonatomic, strong) APIAuthor *author;
@property (nonatomic, copy)   NSString *message;
@property (nonatomic, assign) BOOL isDistinct;
@property (nonatomic, copy)   NSString *url;
@end

@interface APIAuthor : NSObject
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *name;
@end

@interface APIForkee : NSObject
@property (nonatomic, assign)           NSInteger identifier;
@property (nonatomic, copy)             NSString *name;
@property (nonatomic, copy)             NSString *fullName;
@property (nonatomic, strong)           APIUser *owner;
@property (nonatomic, assign)           BOOL isPrivate;
@property (nonatomic, copy)             NSString *htmlURL;
@property (nonatomic, nullable, copy)   NSString *theDescription;
@property (nonatomic, assign)           BOOL isFork;
@property (nonatomic, copy)             NSString *url;
@property (nonatomic, copy)             NSString *forksURL;
@property (nonatomic, copy)             NSString *keysURL;
@property (nonatomic, copy)             NSString *collaboratorsURL;
@property (nonatomic, copy)             NSString *teamsURL;
@property (nonatomic, copy)             NSString *hooksURL;
@property (nonatomic, copy)             NSString *issueEventsURL;
@property (nonatomic, copy)             NSString *eventsURL;
@property (nonatomic, copy)             NSString *assigneesURL;
@property (nonatomic, copy)             NSString *branchesURL;
@property (nonatomic, copy)             NSString *tagsURL;
@property (nonatomic, copy)             NSString *blobsURL;
@property (nonatomic, copy)             NSString *gitTagsURL;
@property (nonatomic, copy)             NSString *gitRefsURL;
@property (nonatomic, copy)             NSString *treesURL;
@property (nonatomic, copy)             NSString *statusesURL;
@property (nonatomic, copy)             NSString *languagesURL;
@property (nonatomic, copy)             NSString *stargazersURL;
@property (nonatomic, copy)             NSString *contributorsURL;
@property (nonatomic, copy)             NSString *subscribersURL;
@property (nonatomic, copy)             NSString *subscriptionURL;
@property (nonatomic, copy)             NSString *commitsURL;
@property (nonatomic, copy)             NSString *gitCommitsURL;
@property (nonatomic, copy)             NSString *commentsURL;
@property (nonatomic, copy)             NSString *issueCommentURL;
@property (nonatomic, copy)             NSString *contentsURL;
@property (nonatomic, copy)             NSString *compareURL;
@property (nonatomic, copy)             NSString *mergesURL;
@property (nonatomic, copy)             NSString *archiveURL;
@property (nonatomic, copy)             NSString *downloadsURL;
@property (nonatomic, copy)             NSString *issuesURL;
@property (nonatomic, copy)             NSString *pullsURL;
@property (nonatomic, copy)             NSString *milestonesURL;
@property (nonatomic, copy)             NSString *notificationsURL;
@property (nonatomic, copy)             NSString *labelsURL;
@property (nonatomic, copy)             NSString *releasesURL;
@property (nonatomic, copy)             NSString *deploymentsURL;
@property (nonatomic, copy)             NSString *createdAt;
@property (nonatomic, copy)             NSString *updatedAt;
@property (nonatomic, copy)             NSString *pushedAt;
@property (nonatomic, copy)             NSString *gitURL;
@property (nonatomic, copy)             NSString *sshURL;
@property (nonatomic, copy)             NSString *cloneURL;
@property (nonatomic, copy)             NSString *svnURL;
@property (nonatomic, nullable, copy)   NSString *homepage;
@property (nonatomic, assign)           NSInteger size;
@property (nonatomic, assign)           NSInteger stargazersCount;
@property (nonatomic, assign)           NSInteger watchersCount;
@property (nonatomic, nullable, copy)   NSString *language;
@property (nonatomic, assign)           BOOL hasIssues;
@property (nonatomic, assign)           BOOL hasProjects;
@property (nonatomic, assign)           BOOL hasDownloads;
@property (nonatomic, assign)           BOOL hasWiki;
@property (nonatomic, assign)           BOOL hasPages;
@property (nonatomic, assign)           NSInteger forksCount;
@property (nonatomic, nullable, copy)   id mirrorURL;
@property (nonatomic, assign)           BOOL isArchived;
@property (nonatomic, assign)           NSInteger openIssuesCount;
@property (nonatomic, nullable, copy)   id license;
@property (nonatomic, assign)           NSInteger forks;
@property (nonatomic, assign)           NSInteger openIssues;
@property (nonatomic, assign)           NSInteger watchers;
@property (nonatomic, copy)             NSString *defaultBranch;
@property (nonatomic, nullable, strong) NSNumber *public;
@end

@interface APIIssue : NSObject
@property (nonatomic, copy)             NSString *url;
@property (nonatomic, copy)             NSString *repositoryURL;
@property (nonatomic, copy)             NSString *labelsURL;
@property (nonatomic, copy)             NSString *commentsURL;
@property (nonatomic, copy)             NSString *eventsURL;
@property (nonatomic, copy)             NSString *htmlURL;
@property (nonatomic, assign)           NSInteger identifier;
@property (nonatomic, assign)           NSInteger number;
@property (nonatomic, copy)             NSString *title;
@property (nonatomic, strong)           APIUser *user;
@property (nonatomic, copy)             NSArray<APILabel *> *labels;
@property (nonatomic, copy)             NSString *state;
@property (nonatomic, assign)           BOOL isLocked;
@property (nonatomic, nullable, strong) APIUser *assignee;
@property (nonatomic, copy)             NSArray<APIUser *> *assignees;
@property (nonatomic, nullable, copy)   id milestone;
@property (nonatomic, assign)           NSInteger comments;
@property (nonatomic, copy)             NSString *createdAt;
@property (nonatomic, copy)             NSString *updatedAt;
@property (nonatomic, nullable, copy)   id closedAt;
@property (nonatomic, copy)             NSString *authorAssociation;
@property (nonatomic, copy)             NSString *body;
@end

@interface APILabel : NSObject
@property (nonatomic, assign) NSInteger identifier;
@property (nonatomic, copy)   NSString *url;
@property (nonatomic, copy)   NSString *name;
@property (nonatomic, copy)   NSString *color;
@property (nonatomic, assign) BOOL isDefault;
@end

@interface APIPullRequest : NSObject
@property (nonatomic, copy)           NSString *url;
@property (nonatomic, assign)         NSInteger identifier;
@property (nonatomic, copy)           NSString *htmlURL;
@property (nonatomic, copy)           NSString *diffURL;
@property (nonatomic, copy)           NSString *patchURL;
@property (nonatomic, copy)           NSString *issueURL;
@property (nonatomic, assign)         NSInteger number;
@property (nonatomic, copy)           NSString *state;
@property (nonatomic, assign)         BOOL isLocked;
@property (nonatomic, copy)           NSString *title;
@property (nonatomic, strong)         APIUser *user;
@property (nonatomic, copy)           NSString *body;
@property (nonatomic, copy)           NSString *createdAt;
@property (nonatomic, copy)           NSString *updatedAt;
@property (nonatomic, nullable, copy) id closedAt;
@property (nonatomic, nullable, copy) id mergedAt;
@property (nonatomic, nullable, copy) id mergeCommitSHA;
@property (nonatomic, nullable, copy) id assignee;
@property (nonatomic, copy)           NSArray *assignees;
@property (nonatomic, copy)           NSArray *requestedReviewers;
@property (nonatomic, copy)           NSArray *requestedTeams;
@property (nonatomic, copy)           NSArray *labels;
@property (nonatomic, nullable, copy) id milestone;
@property (nonatomic, copy)           NSString *commitsURL;
@property (nonatomic, copy)           NSString *reviewCommentsURL;
@property (nonatomic, copy)           NSString *reviewCommentURL;
@property (nonatomic, copy)           NSString *commentsURL;
@property (nonatomic, copy)           NSString *statusesURL;
@property (nonatomic, strong)         APIBase *head;
@property (nonatomic, strong)         APIBase *base;
@property (nonatomic, strong)         APILinks *links;
@property (nonatomic, copy)           NSString *authorAssociation;
@property (nonatomic, assign)         BOOL isMerged;
@property (nonatomic, nullable, copy) id mergeable;
@property (nonatomic, nullable, copy) id rebaseable;
@property (nonatomic, copy)           NSString *mergeableState;
@property (nonatomic, nullable, copy) id mergedBy;
@property (nonatomic, assign)         NSInteger comments;
@property (nonatomic, assign)         NSInteger reviewComments;
@property (nonatomic, assign)         BOOL isMaintainerCanModify;
@property (nonatomic, assign)         NSInteger commits;
@property (nonatomic, assign)         NSInteger additions;
@property (nonatomic, assign)         NSInteger deletions;
@property (nonatomic, assign)         NSInteger changedFiles;
@end

@interface APIBase : NSObject
@property (nonatomic, copy)   NSString *label;
@property (nonatomic, copy)   NSString *ref;
@property (nonatomic, copy)   NSString *sha;
@property (nonatomic, strong) APIUser *user;
@property (nonatomic, strong) APIForkee *repo;
@end

@interface APILinks : NSObject
@property (nonatomic, strong) APIComments *self;
@property (nonatomic, strong) APIComments *html;
@property (nonatomic, strong) APIComments *issue;
@property (nonatomic, strong) APIComments *comments;
@property (nonatomic, strong) APIComments *reviewComments;
@property (nonatomic, strong) APIComments *reviewComment;
@property (nonatomic, strong) APIComments *commits;
@property (nonatomic, strong) APIComments *statuses;
@end

@interface APIComments : NSObject
@property (nonatomic, copy) NSString *href;
@end

@interface APIRepo : NSObject
@property (nonatomic, assign) NSInteger identifier;
@property (nonatomic, copy)   NSString *name;
@property (nonatomic, copy)   NSString *url;
@end

@interface APIGist : NSObject
@property (nonatomic, copy)             NSString *url;
@property (nonatomic, copy)             NSString *forksURL;
@property (nonatomic, copy)             NSString *commitsURL;
@property (nonatomic, copy)             NSString *identifier;
@property (nonatomic, copy)             NSString *gitPullURL;
@property (nonatomic, copy)             NSString *gitPushURL;
@property (nonatomic, copy)             NSString *htmlURL;
@property (nonatomic, copy)             NSDictionary<NSString *, APIFile *> *files;
@property (nonatomic, assign)           BOOL isPublic;
@property (nonatomic, copy)             NSString *createdAt;
@property (nonatomic, copy)             NSString *updatedAt;
@property (nonatomic, nullable, copy)   NSString *theDescription;
@property (nonatomic, assign)           NSInteger comments;
@property (nonatomic, nullable, copy)   id user;
@property (nonatomic, copy)             NSString *commentsURL;
@property (nonatomic, assign)           BOOL isTruncated;
@property (nonatomic, nullable, strong) APIUser *owner;
@end

@interface APIFile : NSObject
@property (nonatomic, copy)           NSString *filename;
@property (nonatomic, assign)         APIFileType *type;
@property (nonatomic, nullable, copy) NSString *language;
@property (nonatomic, copy)           NSString *rawURL;
@property (nonatomic, assign)         NSInteger size;
@end

@interface APIMeta : NSObject
@property (nonatomic, assign) BOOL isVerifiablePasswordAuthentication;
@property (nonatomic, copy)   NSString *githubServicesSHA;
@property (nonatomic, copy)   NSArray<NSString *> *hooks;
@property (nonatomic, copy)   NSArray<NSString *> *git;
@property (nonatomic, copy)   NSArray<NSString *> *pages;
@property (nonatomic, copy)   NSArray<NSString *> *importer;

+ (_Nullable instancetype)fromJSON:(NSString *)json encoding:(NSStringEncoding)encoding error:(NSError *_Nullable *)error;
+ (_Nullable instancetype)fromData:(NSData *)data error:(NSError *_Nullable *)error;
- (NSString *_Nullable)toJSON:(NSStringEncoding)encoding error:(NSError *_Nullable *)error;
- (NSData *_Nullable)toData:(NSError *_Nullable *)error;
@end

NS_ASSUME_NONNULL_END
